//! `atrium::config` — the build **model**.
//!
//! `BuildConfig` is the single, shared description of an image build. Both views
//! construct it: the CLI deserializes it from `--config` JSON, the GUI builds it
//! field-by-field from its widgets. The controllers (`image`, `templates`,
//! `selection`, `preflight`) operate on it. Defining the schema **once** here is
//! what keeps the CLI and GUI in lock-step (no more re-encoding it as JSON in the
//! GUI). Serialize is derived too, so either view can write a build back to disk.

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::path::PathBuf;

/// The 68k launcher (`MacAtrium.bin`) is NOT embedded in this tool — a build reads
/// it from a file (see [`BuildConfig::launcher_bytes`]): `build/MacAtrium.bin`, which
/// Retro68's `cmake --build build` produces, or a prebuilt binary a "release" user
/// drops there. Keeping the binary out of the tool (and out of git) means the build
/// tooling carries only text data, not a compiled artifact.

/// The curated comprehensive library + its compatibility companion, embedded at
/// compile time so a user can build an image without supplying either path. They
/// are the committed `data/*.jsonl` (regenerated by the Library Builder pipeline);
/// a build overrides them per [`BuildConfig::dataset`] / `compatibility`.
pub const EMBEDDED_LIBRARY: &[u8] =
    include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../data/library.jsonl"));
pub const EMBEDDED_COMPAT: &[u8] =
    include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../data/compatibility.jsonl"));
/// The navigation taxonomy + the editable category DB (docs/21), embedded so a
/// build pages the catalog with no extra paths. The DB is regenerated by
/// `atrium library categorize` and hand/GUI-curated.
pub const EMBEDDED_TAXONOMY: &[u8] =
    include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../data/taxonomy.json"));
pub const EMBEDDED_CATEGORIES: &[u8] =
    include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../data/categories.jsonl"));

pub fn d_startup() -> String { "/System Folder/Startup Items".into() }
pub fn d_platform() -> String { "Apple Mac OS".into() }
pub fn d_rbcli() -> String { "rb-cli".into() }
pub fn d_apps_root() -> String { "/MacAtrium/Apps".into() }
pub fn d_metadir() -> String { "/MacAtrium/metadata".into() }
pub fn d_imagesdir() -> String { "/MacAtrium/images".into() }
pub fn d_artdepth() -> String { "8".into() }
pub fn d_curl() -> String { "curl".into() }

/// Default art bound (px) when neither `max_art_size` nor `art_max` is set.
/// The art is never shown truly full-screen: the largest pane is the ~694px-tall
/// info-card / preview art rect on a 1024x768 screen (`H - header - hint -
/// margins`). 720 (that height + headroom) keeps box art pixel-sharp in every
/// view while shrinking a multi-MB scan to a couple hundred KB — DrawPicture
/// renders it fast and it fits a System-6 machine's RAM (an 8.5 MB PoP cover
/// failed to load on 6.0.8). OS 9 builds with a bigger screen can override.
pub const DEFAULT_ART_BOUND: (u32, u32) = (720, 720);
pub fn d_sounds_dir() -> String { "/MacAtrium/sounds".into() }

/// Hard ceiling for a built (bootable) image: 2 GB.
///
/// HFS's *structural* wall is higher — 65535 allocation blocks × 64 KB ≈ 4095 MiB
/// (rb-cli's `expand` will build that; 4096 MiB overshoots by one block) — and the
/// 2 GB→4 GB volume ceiling moved with System 7.5, so a Quadra/7.5.5 could in
/// principle host a larger volume. But whether 7.5.5 *boots* from a >2 GB startup
/// volume is unverified (no q800 boot harness yet), and 6.0.8/7.1 are true 2 GB
/// systems. Until a >2 GB boot volume is proven on the Quadra, every build stays
/// ≤ 2 GB. A future per-target override (gated on 7.5+) could lift this.
pub const MAX_DISK_MB: u64 = 2048;

/// One harvest source: a donor disk image plus the app paths to pull from it.
/// This is the low-level / manual selection path; `Selection` (below) is the
/// higher-level, dataset-driven way to pick apps.
#[derive(Deserialize, Serialize, Clone, Default)]
pub struct HarvestSrc {
    pub image: PathBuf,
    #[serde(default)]
    pub apps: Vec<String>,
    #[serde(default)]
    pub scan: Option<String>,
}

/// How to choose which dataset apps go into the image. Apps are matched against
/// the dataset and harvested from each record's `source` (donor image + path).
#[derive(Deserialize, Serialize, Clone, Debug, PartialEq)]
#[serde(tag = "mode", rename_all = "lowercase")]
pub enum Selection {
    /// Everything in the dataset that is harvestable (has a `source`) and
    /// compatible with the target OS.
    All,
    /// An explicit list of dataset ids — the manual list (handy for testing).
    List {
        #[serde(default)]
        ids: Vec<String>,
    },
    /// Every app whose `categories`/`genre` intersects this list (optional facet).
    Categories {
        #[serde(default)]
        categories: Vec<String>,
    },
}

impl Default for Selection {
    fn default() -> Self {
        Selection::List { ids: Vec::new() }
    }
}

#[derive(Deserialize, Serialize, Clone)]
pub struct BuildConfig {
    /// Base bootable System image to build on top of. Either set this directly,
    /// or set `base_os` to resolve it (+ deploy mode) from the template registry.
    #[serde(default)]
    pub system: Option<PathBuf>,
    /// Template key (e.g. "6.0.8", "7.1") resolved against the template registry
    /// to fill in `system` + deploy mode when those aren't set explicitly.
    #[serde(default)]
    pub base_os: Option<String>,
    /// Output image to produce (overwritten).
    pub out: PathBuf,
    /// The launcher MacBinary to install. `None` (the default) reads
    /// `build/MacAtrium.bin` (or `$MACATRIUM_LAUNCHER`) — see [`Self::launcher_bytes`].
    /// The launcher is never embedded in this tool; you either build it with Retro68
    /// (`cmake --build build`) or drop a release `MacAtrium.bin` into `build/`.
    #[serde(default)]
    pub launcher: Option<PathBuf>,
    /// Curated dataset (the library of titles). `None` (the default) uses the
    /// [`EMBEDDED_LIBRARY`] baked into this tool, so a build needs no library path.
    /// Set it to override (e.g. a work-in-progress `data/library.jsonl`).
    #[serde(default)]
    pub dataset: Option<PathBuf>,
    /// Final image size in MB; the image is grown/kept to fit. Capped at
    /// `MAX_DISK_MB` (2 GB). None = leave the base image's size as-is.
    #[serde(default)]
    pub disk_size_mb: Option<u64>,
    /// Which dataset apps to include. None falls back to the `harvest` block.
    #[serde(default)]
    pub selection: Option<Selection>,
    #[serde(default = "d_startup")]
    pub startup_items: String,
    /// Compatibility/facets overlay (`data/compatibility.jsonl`) merged over the
    /// library at build time (overlay wins): color/mouse/maxDepth/minOS/maxOS/
    /// minMem/minCPU/arch + manual corrections. (The field is still named
    /// `overrides` internally — the generic overlay mechanism; `compatibility` is
    /// accepted as the config key.)
    #[serde(default, alias = "compatibility")]
    pub overrides: Option<PathBuf>,
    /// LaunchBox Metadata.xml — if set, enrich the dataset.
    #[serde(default)]
    pub metadata: Option<PathBuf>,
    /// Macintosh Garden archive root — if set, enrich (68K-only) before LaunchBox
    /// and stage MG box-front/screenshot art for the art pass.
    #[serde(default)]
    pub mg_archive: Option<PathBuf>,
    #[serde(default = "d_platform")]
    pub platform: String,
    /// Auto-detect color/B&W from LaunchBox screenshots during enrich.
    #[serde(default)]
    pub detect_color: bool,
    #[serde(default = "d_curl")]
    pub curl: String,
    /// Apps to harvest from donor images into the output (low-level/manual path).
    #[serde(default)]
    pub harvest: Vec<HarvestSrc>,
    /// Directory of source artwork named `<id>.png` / `.jpg` — converted to PICT.
    #[serde(default)]
    pub art_dir: Option<PathBuf>,
    #[serde(default = "d_artdepth")]
    pub art_depth: String,
    /// Generate multiple depth variants (e.g. ["1","8"]) named `<id>.<depth>.pict`.
    #[serde(default)]
    pub art_depths: Vec<String>,
    /// Pack each item's depth variants into ONE per-item resource fork
    /// (`images/<id>.rsrc`: a 1-bit `ABMP` + a `PICT` per colour depth, id =
    /// 128+bits) instead of loose `.pict`/`.raw` files — far fewer files on the
    /// volume (docs/36 Phase 1). The launcher tries `.rsrc` first, else loose files.
    #[serde(default)]
    pub art_forks: bool,
    /// Legacy: downscale art so its longest side is at most this many pixels
    /// (a square bound). Prefer `max_art_size`. When neither is set the default
    /// bound applies (see [`BuildConfig::art_bounds`]).
    #[serde(default)]
    pub art_max: Option<u32>,
    /// Downscale art to fit within this pixel box, written `"WxH"` (e.g.
    /// `"1024x768"` for a classic Mac, `"1280x854"` on OS 9). Aspect is kept and
    /// art is never upscaled. Sized so the full-screen preview is sharp at the
    /// target resolution while box-art scans don't bake into multi-MB PICTs.
    /// Takes precedence over `art_max`; default `1024x768` (see `art_bounds`).
    #[serde(default)]
    pub max_art_size: Option<String>,
    /// Download Box-Front art from LaunchBox (needs `metadata`).
    #[serde(default)]
    pub download_art: bool,
    #[serde(default = "d_rbcli")]
    pub rb_cli: String,
    #[serde(default = "d_apps_root")]
    pub apps_root: String,
    #[serde(default = "d_metadir")]
    pub metadata_dir: String,
    #[serde(default = "d_imagesdir")]
    pub images_dir: String,
    /// Staging dir for intermediates (default: a temp dir).
    #[serde(default)]
    pub stage: Option<PathBuf>,
    /// Optional startup chime (PCM WAV) baked into the image.
    #[serde(default)]
    pub startup_sound: Option<PathBuf>,
    /// Optional shutdown chime (PCM WAV).
    #[serde(default)]
    pub shutdown_sound: Option<PathBuf>,
    /// Where the chimes live on the volume.
    #[serde(default = "d_sounds_dir")]
    pub sounds_dir: String,
    /// System 6 appliance: install the launcher *as* the Finder (FNDR/MACS) so the
    /// boot launches it as the shell. Leave false for the 7.x Startup-Items deploy.
    #[serde(default)]
    pub finder_replace: bool,
    /// Memory partition baked into the launcher's `'SIZE'` (-1) resource for this
    /// build, as `[preferred_kb, minimum_kb]`. `None` keeps the launcher binary's
    /// built-in 2 MB / 1 MB. Set it small for a compact B&W target (Mac Plus/SE)
    /// where 2 MB starves System 6 + the launched game — see `effective_app_mem`.
    #[serde(default)]
    pub app_mem_kb: Option<[u32; 2]>,
}

/// Recommended colour-build (System 7.x) partition in KB: `(preferred, minimum)`.
/// A 7.x colour build's measured partition peak is ~472 KB — the off-screen GWorld
/// is allocated from temp memory (`useTempMem`), so it doesn't land here; 1024/768
/// leaves headroom for a larger library and the GWorld-falls-to-heap fallback.
pub const COLOR_APP_MEM_KB: (u32, u32) = (1024, 768);

/// The compact B&W (Mac Plus/SE) partition default in KB: `(preferred, minimum)`.
/// These machines cap at 4 MB total, draw 1-bit direct (no off-screen GWorld) and
/// load only small 1-bit `.raw` art, so the shell's real peak is a few hundred KB.
/// 512/384 is verified in Snow: a 6.0.8 B&W appliance boots, loads its catalog,
/// navigates (cover load/dispose churn) and launches a game inside this partition.
pub const COMPACT_APP_MEM_KB: (u32, u32) = (512, 384);

/// A filesystem-safe base name for an item's baked art/icon files (the catalog
/// `art` base). Classic HFS caps filenames at 31 chars and the longest art suffix
/// is `.shot.24.pict` (13), so the base must be ≤ 18; a longer id is truncated to
/// 12 chars + a short hash for uniqueness. The catalog `id` itself is untouched —
/// only on-volume art filenames (and the `art` base pointing at them) use this.
/// Shared by the build's art pass and the catalog generator so both agree, and so
/// the launcher can resolve `images/<art>` from the stored base.
pub fn fs_id(id: &str) -> String {
    const MAX: usize = 17;
    if id.len() <= MAX {
        return id.to_string();
    }
    let mut h: u32 = 0x811c_9dc5; // FNV-1a
    for b in id.bytes() {
        h ^= b as u32;
        h = h.wrapping_mul(0x0100_0193);
    }
    format!("{}-{:04x}", &id[..MAX - 5], h & 0xffff)
}

/// Parse a `"WxH"` art-size string (e.g. `"1024x768"`) into `(w, h)`. Accepts a
/// lower- or upper-case `x` separator; returns `None` on any malformed/zero input.
pub fn parse_wh(s: &str) -> Option<(u32, u32)> {
    let mut it = s.trim().split(['x', 'X']);
    let w: u32 = it.next()?.trim().parse().ok()?;
    let h: u32 = it.next()?.trim().parse().ok()?;
    if it.next().is_some() || w == 0 || h == 0 {
        return None;
    }
    Some((w, h))
}

impl BuildConfig {
    /// Pixel box `(w, h)` to downscale art into: `max_art_size` (`"WxH"`) if set
    /// and parseable, else the legacy `art_max` as a square bound, else
    /// [`DEFAULT_ART_BOUND`]. Art is fit within the box (aspect kept, never upscaled).
    pub fn art_bounds(&self) -> (u32, u32) {
        if let Some(wh) = self.max_art_size.as_deref().and_then(parse_wh) {
            return wh;
        }
        if let Some(n) = self.art_max {
            return (n, n);
        }
        DEFAULT_ART_BOUND
    }

    /// Whether this build wants colour artwork — true when `art_depths` requests
    /// any depth above 1-bit. A 1-bit-only build (`["1"]`, the Mac Plus / SE
    /// target) is pure black & white: the colour box-art PICTs and the colour
    /// `icl8` icon PICT are skipped, so the image (and the launcher's runtime
    /// memory) shrink to just the 1-bit `.raw` art a compact Mac can use.
    pub fn wants_color_art(&self) -> bool {
        self.art_depths.iter().any(|d| d.trim() != "1")
    }

    /// The launcher memory partition `(preferred_kb, minimum_kb)` to bake in, or
    /// `None` to leave the binary's built-in 2 MB / 1 MB. An explicit `app_mem_kb`
    /// always wins. `minimum` is clamped to be <= `preferred` (the Process Manager
    /// requires it). Deliberately *not* auto-derived from B&W art: a B&W-art build
    /// can still run on a colour screen (paying for the off-screen GWorld), so the
    /// small partition is opted into explicitly for the compact target.
    pub fn effective_app_mem(&self) -> Option<(u32, u32)> {
        self.app_mem_kb.map(|[p, m]| (p, m.min(p)))
    }

    /// The path the launcher MacBinary is read from: [`Self::launcher`] if set, else
    /// `$MACATRIUM_LAUNCHER`, else `build/MacAtrium.bin` (relative to the working dir —
    /// the same convention as `data/templates.json`). It is NOT embedded in this tool.
    pub fn launcher_path(&self) -> PathBuf {
        self.launcher
            .clone()
            .or_else(|| std::env::var_os("MACATRIUM_LAUNCHER").map(PathBuf::from))
            .unwrap_or_else(|| PathBuf::from("build/MacAtrium.bin"))
    }

    /// The launcher MacBinary bytes to install, read from [`Self::launcher_path`].
    /// (The bytes are patched — name, bundle bit, `SIZE` — before injection, so the
    /// on-disk file is never mutated.) A missing file is a clear, actionable error:
    /// build it with Retro68 (`cmake --build build`) or drop a release binary there.
    pub fn launcher_bytes(&self) -> Result<Vec<u8>> {
        let path = self.launcher_path();
        std::fs::read(&path).with_context(|| {
            format!(
                "reading launcher {} — build it with Retro68 (cmake --build build) or \
                 drop a prebuilt MacAtrium.bin there",
                path.display()
            )
        })
    }

    /// The library (dataset) bytes: the file at [`Self::dataset`] if set, otherwise
    /// the [`EMBEDDED_LIBRARY`] — so a build needs no library path.
    pub fn dataset_bytes(&self) -> Result<Vec<u8>> {
        match &self.dataset {
            Some(p) => std::fs::read(p).with_context(|| format!("reading dataset {}", p.display())),
            None => Ok(EMBEDDED_LIBRARY.to_vec()),
        }
    }

    /// The compatibility-overlay bytes: the file at `overrides` (the `compatibility`
    /// key) if set, otherwise the [`EMBEDDED_COMPAT`] — so the requirements/facets
    /// overlay is always applied even when no path is given.
    pub fn compatibility_bytes(&self) -> Result<Vec<u8>> {
        match &self.overrides {
            Some(p) => std::fs::read(p)
                .with_context(|| format!("reading compatibility {}", p.display())),
            None => Ok(EMBEDDED_COMPAT.to_vec()),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fs_id_keeps_short_ids_and_shrinks_long_ones() {
        assert_eq!(fs_id("dark-castle"), "dark-castle"); // short -> unchanged
        let long = "armor-alley-level-editor-2-0"; // 28 chars
        let got = fs_id(long);
        assert!(got.len() <= 17, "fs_id too long: {got} ({})", got.len());
        // longest baked suffix is ".shot.24.pict" (13) -> must fit 31-char HFS.
        assert!(got.len() + ".shot.24.pict".len() <= 31);
        assert_eq!(fs_id(long), got); // deterministic
        assert_ne!(fs_id("a-very-long-game-name-one"), fs_id("a-very-long-game-name-two"));
    }

    #[test]
    fn app_mem_kb_round_trips_and_clamps() {
        // The field both the GUI Save/Load and the `atrium image` CLI rely on.
        let mut c = BuildConfig::default();
        assert_eq!(c.effective_app_mem(), None); // absent -> launcher default

        c.app_mem_kb = Some([COLOR_APP_MEM_KB.0, COLOR_APP_MEM_KB.1]);
        let json = serde_json::to_string(&c).unwrap();
        let back: BuildConfig = serde_json::from_str(&json).unwrap();
        assert_eq!(back.app_mem_kb, Some([1024, 768]));
        assert_eq!(back.effective_app_mem(), Some((1024, 768)));

        // minimum is clamped to <= preferred.
        c.app_mem_kb = Some([512, 999]);
        assert_eq!(c.effective_app_mem(), Some((512, 512)));
    }

    #[test]
    fn omitted_app_mem_kb_deserializes_to_none() {
        // A legacy config without the field must still load (serde default).
        let c: BuildConfig =
            serde_json::from_str(r#"{"out":"o","dataset":"d"}"#).unwrap();
        assert_eq!(c.app_mem_kb, None);
        assert_eq!(c.launcher, None); // launcher is optional -> resolved to a path
    }

    #[test]
    fn launcher_path_defaults_to_build_dir() {
        // No config path + no env override -> build/MacAtrium.bin (the launcher is
        // never embedded; it's built by Retro68 or dropped in from a release).
        let c = BuildConfig::default();
        assert_eq!(c.launcher_path(), PathBuf::from("build/MacAtrium.bin"));
    }

    #[test]
    fn launcher_path_honors_config() {
        let c: BuildConfig =
            serde_json::from_str(r#"{"out":"o","launcher":"/x/MacAtrium.bin"}"#).unwrap();
        assert_eq!(c.launcher_path(), PathBuf::from("/x/MacAtrium.bin"));
    }

    #[test]
    fn dataset_and_compatibility_default_to_embedded() {
        let c = BuildConfig::default(); // dataset/overrides: None
        assert_eq!(c.dataset_bytes().unwrap(), EMBEDDED_LIBRARY);
        assert_eq!(c.compatibility_bytes().unwrap(), EMBEDDED_COMPAT);
        // sanity: the bundled library is real JSONL, the compat overlay non-empty
        assert!(EMBEDDED_LIBRARY.len() > 1000 && EMBEDDED_LIBRARY.contains(&b'{'));
        assert!(!EMBEDDED_COMPAT.is_empty());
    }
}

impl Default for BuildConfig {
    fn default() -> Self {
        BuildConfig {
            system: None,
            base_os: None,
            out: PathBuf::new(),
            launcher: None,
            dataset: None,
            disk_size_mb: None,
            selection: None,
            startup_items: d_startup(),
            overrides: None,
            metadata: None,
            mg_archive: None,
            platform: d_platform(),
            detect_color: false,
            curl: d_curl(),
            harvest: Vec::new(),
            art_dir: None,
            art_depth: d_artdepth(),
            art_depths: Vec::new(),
            art_forks: false,
            art_max: None,
            max_art_size: None,
            download_art: false,
            rb_cli: d_rbcli(),
            apps_root: d_apps_root(),
            metadata_dir: d_metadir(),
            images_dir: d_imagesdir(),
            stage: None,
            startup_sound: None,
            shutdown_sound: None,
            sounds_dir: d_sounds_dir(),
            finder_replace: false,
            app_mem_kb: None,
        }
    }
}
