//! `atrium::config` — the build **model**.
//!
//! `BuildConfig` is the single, shared description of an image build. Both views
//! construct it: the CLI deserializes it from `--config` JSON, the GUI builds it
//! field-by-field from its widgets. The controllers (`image`, `templates`,
//! `selection`, `preflight`) operate on it. Defining the schema **once** here is
//! what keeps the CLI and GUI in lock-step (no more re-encoding it as JSON in the
//! GUI). Serialize is derived too, so either view can write a build back to disk.

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::path::PathBuf;

/// The 68k launcher (`MacAtrium.bin`) is NOT embedded in this tool — a build reads
/// it from a file (see [`BuildConfig::launcher_bytes`]): `build/MacAtrium.bin`, which
/// Retro68's `cmake --build build` produces, or a prebuilt binary a "release" user
/// drops there. Keeping the binary out of the tool (and out of git) means the build
/// tooling carries only text data, not a compiled artifact.

/// The curated comprehensive library + its compatibility companion, embedded at
/// compile time so a user can build an image without supplying either path. They
/// are the committed `data/*.jsonl` (regenerated by the Library Builder pipeline);
/// a build overrides them per [`BuildConfig::dataset`] / `compatibility`.
pub const EMBEDDED_LIBRARY: &[u8] =
    include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../data/library.jsonl"));
pub const EMBEDDED_COMPAT: &[u8] =
    include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../data/compatibility.jsonl"));
/// The navigation taxonomy + the editable category DB (docs/21), embedded so a
/// build pages the catalog with no extra paths. The DB is regenerated by
/// `atrium library categorize` and hand/GUI-curated.
pub const EMBEDDED_TAXONOMY: &[u8] =
    include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../data/taxonomy.json"));
pub const EMBEDDED_CATEGORIES: &[u8] =
    include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../data/categories.jsonl"));
/// The per-title runtime **dependency** registry (`data/dependencies.json`): a
/// dep-id → {name, source, install_os, note} map (a `"//"` documentation key is
/// skipped by the loader). Embedded so a build resolves a title's `requires:[…]`
/// facet with no extra paths — mirrors the library / compatibility / taxonomy /
/// targets embeds. User entries under `~/.macatrium.json` `"dependencies"` overlay
/// it (see [`dependencies`]). Kept as text (`include_str!`) so the loader parses it
/// straight into a `serde_json::Map`.
pub const EMBEDDED_DEPENDENCIES: &str =
    include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../data/dependencies.json"));

pub fn d_startup() -> String { "/System Folder/Startup Items".into() }
pub fn d_platform() -> String { "Apple Mac OS".into() }
pub fn d_rbcli() -> String { "rb-cli".into() }
pub fn d_apps_root() -> String { "/MacAtrium/Apps".into() }
pub fn d_metadir() -> String { "/MacAtrium/metadata".into() }
pub fn d_imagesdir() -> String { "/MacAtrium/images".into() }
pub fn d_artdepth() -> String { "8".into() }
/// Default depth variants: all three art modes (1/8/24-bit, docs/44), so a build
/// bakes B&W + 8-bit colour + 24-bit truecolour unless a config/Target overrides.
pub fn d_art_depths() -> Vec<String> { vec!["1".into(), "8".into(), "24".into()] }
pub fn d_curl() -> String { "curl".into() }

/// Default art bound (px) when neither `max_art_size` nor `art_max` is set.
/// The art is never shown truly full-screen: the largest pane is the ~694px-tall
/// info-card / preview art rect on a 1024x768 screen (`H - header - hint -
/// margins`). 720 (that height + headroom) keeps box art pixel-sharp in every
/// view while shrinking a multi-MB scan to a couple hundred KB — DrawPicture
/// renders it fast and it fits a System-6 machine's RAM (an 8.5 MB PoP cover
/// failed to load on 6.0.8). OS 9 builds with a bigger screen can override.
pub const DEFAULT_ART_BOUND: (u32, u32) = (720, 720);
pub fn d_sounds_dir() -> String { "/MacAtrium/sounds".into() }

/// Hard ceiling for a built (bootable) image: 2 GB.
///
/// HFS's *structural* wall is higher — 65535 allocation blocks × 64 KB ≈ 4095 MiB
/// (rb-cli's `expand` will build that; 4096 MiB overshoots by one block) — and the
/// 2 GB→4 GB volume ceiling moved with System 7.5, so a Quadra/7.5.5 could in
/// principle host a larger volume. But whether 7.5.5 *boots* from a >2 GB startup
/// volume is unverified (no q800 boot harness yet), and 6.0.8/7.1 are true 2 GB
/// systems. Until a >2 GB boot volume is proven on the Quadra, every build stays
/// ≤ 2 GB. A future per-target override (gated on 7.5+) could lift this.
pub const MAX_DISK_MB: u64 = 2048;

/// One harvest source: a donor disk image plus the app paths to pull from it.
/// This is the low-level / manual selection path; `Selection` (below) is the
/// higher-level, dataset-driven way to pick apps.
#[derive(Deserialize, Serialize, Clone, Default)]
pub struct HarvestSrc {
    pub image: PathBuf,
    #[serde(default)]
    pub apps: Vec<String>,
    #[serde(default)]
    pub scan: Option<String>,
}

/// The reservoir **source** a runtime dependency's files are copied from: a donor
/// *key* (resolved through [`donors`](crate::donors), exactly like a title's
/// `harvest_src`) plus the path to the dep's files on that donor. Same `{donor,
/// path}` shape the dataset's `harvest_src` uses — the files are copied **verbatim**
/// (image-to-image `rb-cli cp`), the same mechanism reservoir games use. (Distinct
/// from [`HarvestSrc`], which is the manual `{image, apps}` harvest-config source.)
#[derive(Deserialize, Serialize, Clone, Debug)]
pub struct DepSource {
    /// Donor key into `donors.json` (e.g. "macgarden") — resolved to a disk image.
    pub donor: String,
    /// Path to the dep's files on that donor (its contents are copied verbatim).
    pub path: String,
}

/// A per-title runtime **dependency**: a system Extension the OS needs but doesn't
/// bundle (e.g. Sound Manager 3.0 on System 7.1). A title declares
/// `requires:[<dep-id>]` (a compatibility facet); a build installs each required
/// dep's files (from its [`DepSource`]) into every System Folder whose name matches
/// one of [`install_os`](Dependency::install_os). Bundled in
/// [`EMBEDDED_DEPENDENCIES`], user-overridable via `~/.macatrium.json` — mirroring
/// the [`Target`](crate::targets::Target) bundled⊕user pattern.
#[derive(Deserialize, Serialize, Clone, Debug)]
pub struct Dependency {
    /// Human name, for the build log (e.g. "Sound Manager 3.0").
    pub name: String,
    /// Where the dep's files come from (a reservoir donor key + path).
    pub source: DepSource,
    /// The OS versions that actually need this dep. Each entry is **substring**-
    /// matched against a System Folder's name (e.g. "7.1" matches "System Folder
    /// 7.1"). Empty = a deliberate no-op: the dep isn't staged yet, or no OS on the
    /// disk needs it (OS versions not listed bundle it already or predate it).
    #[serde(default)]
    pub install_os: Vec<String>,
    /// Optional curator note (provenance / why these OS versions). Not read by the
    /// build; documentation only.
    #[serde(default)]
    pub note: Option<String>,
    /// Files (each relative to a System Folder, e.g. "Extensions/Sound Manager")
    /// whose presence means the dep is already satisfied *there* — the base System
    /// (or an earlier step) already ships it, often a newer build. If any is present
    /// in a target folder, the install is skipped so a build never downgrades the
    /// base. Empty = no check (install wherever `install_os` matches). Presence-only;
    /// no version comparison.
    #[serde(default)]
    pub satisfied_if: Vec<String>,
}

/// Parse a dependency-registry JSON object (dep-id → [`Dependency`]) from text,
/// **skipping any key that starts with `/`** — the committed `data/dependencies.json`
/// carries a `"//"` documentation key that is not a dependency. A malformed entry is
/// skipped with a warning (fail-soft), not aborted. Pure (no I/O), so it stays
/// deterministic and unit-testable; [`dependencies`] wraps it with the user overlay.
fn parse_dependencies(json: &str) -> std::collections::HashMap<String, Dependency> {
    let mut out = std::collections::HashMap::new();
    let map: serde_json::Map<String, serde_json::Value> = match serde_json::from_str(json) {
        Ok(m) => m,
        Err(e) => {
            eprintln!("[deps] WARNING: dependency registry is not valid JSON: {e}");
            return out;
        }
    };
    for (id, v) in map {
        if id.starts_with('/') {
            continue; // "//" documentation key — not a dependency
        }
        match serde_json::from_value::<Dependency>(v) {
            Ok(dep) => {
                out.insert(id, dep);
            }
            Err(e) => eprintln!("[deps] WARNING: skipping malformed dependency {id:?}: {e}"),
        }
    }
    out
}

/// The dependency registry a build resolves `requires:[…]` against: the bundled
/// [`EMBEDDED_DEPENDENCIES`] overlaid with the user's `"dependencies"` entries from
/// `~/.macatrium.json` (a user entry wins on an id collision), mirroring the Targets
/// bundled⊕user pattern.
pub fn dependencies() -> std::collections::HashMap<String, Dependency> {
    let mut reg = parse_dependencies(EMBEDDED_DEPENDENCIES);
    reg.extend(crate::settings::Settings::load_default().dependencies);
    reg
}

/// How to choose which dataset apps go into the image. Apps are matched against
/// the dataset and harvested from each record's `source` (donor image + path).
#[derive(Deserialize, Serialize, Clone, Debug, PartialEq)]
#[serde(tag = "mode", rename_all = "lowercase")]
pub enum Selection {
    /// Everything in the dataset that is harvestable (has a `source`) and
    /// compatible with the target OS.
    All,
    /// An explicit list of dataset ids — the manual list (handy for testing).
    List {
        #[serde(default)]
        ids: Vec<String>,
    },
    /// Every app whose `categories`/`genre` intersects this list (optional facet).
    Categories {
        #[serde(default)]
        categories: Vec<String>,
    },
}

impl Default for Selection {
    fn default() -> Self {
        Selection::List { ids: Vec::new() }
    }
}

#[derive(Deserialize, Serialize, Clone)]
pub struct BuildConfig {
    /// Base bootable System image to build on top of. Either set this directly,
    /// or set `base_os` to resolve it (+ deploy mode) from the template registry.
    #[serde(default)]
    pub system: Option<PathBuf>,
    /// Template key (e.g. "6.0.8", "7.1") resolved against the template registry
    /// to fill in `system` + deploy mode when those aren't set explicitly.
    #[serde(default)]
    pub base_os: Option<String>,
    /// Output image to produce (overwritten).
    pub out: PathBuf,
    /// The launcher MacBinary to install. `None` (the default) reads
    /// `build/MacAtrium.bin` (or `$MACATRIUM_LAUNCHER`) — see [`Self::launcher_bytes`].
    /// The launcher is never embedded in this tool; you either build it with Retro68
    /// (`cmake --build build`) or drop a release `MacAtrium.bin` into `build/`.
    #[serde(default)]
    pub launcher: Option<PathBuf>,
    /// Curated dataset (the library of titles). `None` (the default) uses the
    /// [`EMBEDDED_LIBRARY`] baked into this tool, so a build needs no library path.
    /// Set it to override (e.g. a work-in-progress `data/library.jsonl`).
    #[serde(default)]
    pub dataset: Option<PathBuf>,
    /// Final image size in MB; the image is grown/kept to fit. Capped at
    /// `MAX_DISK_MB` (2 GB). None = leave the base image's size as-is.
    #[serde(default)]
    pub disk_size_mb: Option<u64>,
    /// Which dataset apps to include. None falls back to the `harvest` block.
    #[serde(default)]
    pub selection: Option<Selection>,
    /// Build from a named **collection** (a saved game list — `data/collections/
    /// <name>.json`, or a user collection under `~/.macatrium/collections`). Its
    /// `ids` become the selection and its per-title `overrides` merge over the
    /// dataset. Takes precedence over `selection` when set.
    #[serde(default)]
    pub collection: Option<String>,
    #[serde(default = "d_startup")]
    pub startup_items: String,
    /// Compatibility/facets overlay (`data/compatibility.jsonl`) merged over the
    /// library at build time (overlay wins): color/mouse/maxDepth/minOS/maxOS/
    /// minMem/minCPU/arch + manual corrections. (The field is still named
    /// `overrides` internally — the generic overlay mechanism; `compatibility` is
    /// accepted as the config key.)
    #[serde(default, alias = "compatibility")]
    pub overrides: Option<PathBuf>,
    /// LaunchBox Metadata.xml — if set, enrich the dataset.
    #[serde(default)]
    pub metadata: Option<PathBuf>,
    /// Macintosh Garden archive root — if set, enrich (68K-only) before LaunchBox
    /// and stage MG box-front/screenshot art for the art pass.
    #[serde(default)]
    pub mg_archive: Option<PathBuf>,
    #[serde(default = "d_platform")]
    pub platform: String,
    /// Auto-detect color/B&W from LaunchBox screenshots during enrich.
    #[serde(default)]
    pub detect_color: bool,
    #[serde(default = "d_curl")]
    pub curl: String,
    /// Apps to harvest from donor images into the output (low-level/manual path).
    #[serde(default)]
    pub harvest: Vec<HarvestSrc>,
    /// Directory of source artwork named `<id>.png` / `.jpg` — converted to PICT.
    #[serde(default)]
    pub art_dir: Option<PathBuf>,
    #[serde(default = "d_artdepth")]
    pub art_depth: String,
    /// Generate multiple depth variants (e.g. ["1","8"]) named `<id>.<depth>.pict`.
    /// Defaults to all three art modes (`["1","8","24"]`, docs/44) so a build bakes
    /// B&W + colour + truecolour; set explicitly to override — e.g. `["1"]` for a
    /// pure-B&W compact build, or `[]` to fall back to the single `art_depth`.
    #[serde(default = "d_art_depths")]
    pub art_depths: Vec<String>,
    /// Pack each item's depth variants into ONE per-item resource fork
    /// (`images/<id>.rsrc`: a 1-bit `ABMP` + a `PICT` per colour depth, id =
    /// 128+bits) instead of loose `.pict`/`.raw` files — far fewer files on the
    /// volume (docs/36 Phase 1). The launcher tries `.rsrc` first, else loose files.
    /// Defaults ON as of Phase 1 completion; set false to keep the loose-file layout.
    #[serde(default = "d_art_forks")]
    pub art_forks: bool,
    /// Legacy: downscale art so its longest side is at most this many pixels
    /// (a square bound). Prefer `max_art_size`. When neither is set the default
    /// bound applies (see [`BuildConfig::art_bounds`]).
    #[serde(default)]
    pub art_max: Option<u32>,
    /// Downscale art to fit within this pixel box, written `"WxH"` (e.g.
    /// `"1024x768"` for a classic Mac, `"1280x854"` on OS 9). Aspect is kept and
    /// art is never upscaled. Sized so the full-screen preview is sharp at the
    /// target resolution while box-art scans don't bake into multi-MB PICTs.
    /// Takes precedence over `art_max`; default `1024x768` (see `art_bounds`).
    #[serde(default)]
    pub max_art_size: Option<String>,
    /// Download Box-Front art from LaunchBox (needs `metadata`).
    #[serde(default)]
    pub download_art: bool,
    #[serde(default = "d_rbcli")]
    pub rb_cli: String,
    #[serde(default = "d_apps_root")]
    pub apps_root: String,
    #[serde(default = "d_metadir")]
    pub metadata_dir: String,
    #[serde(default = "d_imagesdir")]
    pub images_dir: String,
    /// Staging dir for intermediates (default: a temp dir).
    #[serde(default)]
    pub stage: Option<PathBuf>,
    /// Optional startup chime (PCM WAV) baked into the image.
    #[serde(default)]
    pub startup_sound: Option<PathBuf>,
    /// Optional shutdown chime (PCM WAV).
    #[serde(default)]
    pub shutdown_sound: Option<PathBuf>,
    /// After the build, boot 7.5.5 in Snow so the Finder rebuilds the volume's
    /// Desktop database, then cleanly shut down and re-bless 7.1. Default on;
    /// a no-op unless `snow_harness`/`snow_rom`/`snow_mdc_rom` are all set.
    #[serde(default = "d_rebuild_desktop")]
    pub rebuild_desktop: bool,
    /// Path to the Snow harness binary (`macatrium_harness`) — machine-local, like
    /// `rb_cli`. Required for `rebuild_desktop`; absent ⇒ the rebuild is skipped.
    #[serde(default)]
    pub snow_harness: Option<String>,
    /// Mac II ROM for the Snow harness.
    #[serde(default)]
    pub snow_rom: Option<String>,
    /// Macintosh Display Card ROM for the Snow harness.
    #[serde(default)]
    pub snow_mdc_rom: Option<String>,
    /// Right-size the finished image: after every content step, shrink the volume so
    /// free space is `free_space_pct`% of the disk (min `free_space_min_mb` MB on a
    /// small disk), reclaiming the slack from growing to the working `disk_size_mb`.
    /// Default on; `expand` re-wraps the clone bootable (blessed System Folder + boot
    /// blocks preserved), and the target never exceeds the current size or the 2 GB cap.
    #[serde(default = "d_right_size")]
    pub right_size: bool,
    /// Free space as a percent of the final disk when `right_size` is on (default 10).
    #[serde(default = "d_free_space_pct")]
    pub free_space_pct: u64,
    /// Floor on free space (MB) for a small disk, where the percent would be less (30).
    #[serde(default = "d_free_space_min_mb")]
    pub free_space_min_mb: u64,
    /// Where the chimes live on the volume.
    #[serde(default = "d_sounds_dir")]
    pub sounds_dir: String,
    /// System 6 appliance: install the launcher *as* the Finder (FNDR/MACS) so the
    /// boot launches it as the shell. Leave false for the 7.x Startup-Items deploy.
    #[serde(default)]
    pub finder_replace: bool,
    /// Multi-System appliance: install the launcher into **every** System Folder on
    /// the volume — Startup Items for System 7+, as the Finder for System 6.0.x — so
    /// blessing/booting any System on the disk lands back in MacAtrium instead of that
    /// System's Finder. Pairs with the in-UI OS chooser (docs/36 Phase 2, docs/40).
    /// Pre-6 folders (System 4/5, below the 6.0.4 Gestalt floor) are skipped. Default
    /// false = single-folder install per `finder_replace` / `startup_items`.
    #[serde(default)]
    pub install_all_systems: bool,
    /// Memory partition baked into the launcher's `'SIZE'` (-1) resource for this
    /// build, as `[preferred_kb, minimum_kb]`. `None` keeps the launcher binary's
    /// built-in 2 MB / 1 MB. Set it small for a compact B&W target (Mac Plus/SE)
    /// where 2 MB starves System 6 + the launched game — see `effective_app_mem`.
    #[serde(default)]
    pub app_mem_kb: Option<[u32; 2]>,
    /// Control panels to remove from the target System Folder at build time so they
    /// don't float over the full-screen launcher — the Mac OS 8 **Control Strip** and
    /// **Launcher** quick-launch surfaces (docs/36). Matched case-insensitively;
    /// absent names are a no-op (System 6 / 7.1 don't ship them). Set to `[]` to keep
    /// everything.
    #[serde(default = "d_disable_cdevs")]
    pub disable_control_panels: Vec<String>,
}

/// `art_forks` defaults ON (Phase 1 complete, docs/36): builds pack art into
/// per-item `images/<id>.rsrc` unless a config sets `"art_forks": false`.
pub fn d_art_forks() -> bool { true }
pub fn d_rebuild_desktop() -> bool { true }
pub fn d_right_size() -> bool { true }
pub fn d_free_space_pct() -> u64 { 10 }
pub fn d_free_space_min_mb() -> u64 { 30 }

/// Appliance cleanup default: quick-launch control panels removed from the target
/// System Folder so they don't overlay the full-screen launcher (docs/36). No-op
/// where absent (System 6 / 7.1 don't ship them).
pub fn d_disable_cdevs() -> Vec<String> {
    vec!["Control Strip".into(), "Launcher".into()]
}

/// Recommended colour-build (System 7.x) partition in KB: `(preferred, minimum)`.
/// A 7.x colour build's measured partition peak is ~472 KB — the off-screen GWorld
/// is allocated from temp memory (`useTempMem`), so it doesn't land here; 1024/768
/// leaves headroom for a larger library and the GWorld-falls-to-heap fallback.
pub const COLOR_APP_MEM_KB: (u32, u32) = (1024, 768);

/// The compact B&W (Mac Plus/SE) partition default in KB: `(preferred, minimum)`.
/// These machines cap at 4 MB total, draw 1-bit direct (no off-screen GWorld) and
/// load only small 1-bit `.raw` art, so the shell's real peak is a few hundred KB.
/// 512/384 is verified in Snow: a 6.0.8 B&W appliance boots, loads its catalog,
/// navigates (cover load/dispose churn) and launches a game inside this partition.
pub const COMPACT_APP_MEM_KB: (u32, u32) = (512, 384);

/// A filesystem-safe base name for an item's baked art/icon files (the catalog
/// `art` base). Classic HFS caps filenames at 31 chars and the longest art suffix
/// is `.shot.24.pict` (13), so the base must be ≤ 18; a longer id is truncated to
/// 12 chars + a short hash for uniqueness. The catalog `id` itself is untouched —
/// only on-volume art filenames (and the `art` base pointing at them) use this.
/// Shared by the build's art pass and the catalog generator so both agree, and so
/// the launcher can resolve `images/<art>` from the stored base.
pub fn fs_id(id: &str) -> String {
    const MAX: usize = 17;
    if id.len() <= MAX {
        return id.to_string();
    }
    let mut h: u32 = 0x811c_9dc5; // FNV-1a
    for b in id.bytes() {
        h ^= b as u32;
        h = h.wrapping_mul(0x0100_0193);
    }
    format!("{}-{:04x}", &id[..MAX - 5], h & 0xffff)
}

/// Shorten a display title into a classic-HFS-safe **on-volume folder/file name**:
/// **≤ 31 characters** (the HFS filename cap). A short name is returned unchanged;
/// a longer one becomes a readable 26-char prefix + `-` + a 4-hex hash of the full
/// name, so two distinct long titles never collapse to the same 31 chars — which
/// is exactly how the HFS truncation of "Where in America's Past Is Carmen
/// Sandiego" → "…Is Carm" made the title ambiguous. Deterministic and
/// char-boundary-safe (titles carry `™`/`ƒ`; MacRoman is single-byte so char
/// count ≈ the on-volume byte count). Use this whenever the tooling *creates* an
/// on-volume name from a title, so a name is never silently mangled by HFS
/// (docs/CODE_GUIDELINES.md). The catalog `id` and display `name` are untouched.
pub fn hfs_name(name: &str) -> String {
    const MAX: usize = 31;
    if name.chars().count() <= MAX {
        return name.to_string();
    }
    let mut h: u32 = 0x811c_9dc5; // FNV-1a over the full name
    for b in name.bytes() {
        h ^= b as u32;
        h = h.wrapping_mul(0x0100_0193);
    }
    let prefix: String = name.chars().take(MAX - 5).collect(); // 26 + '-' + 4 = 31
    format!("{prefix}-{:04x}", h & 0xffff)
}

/// Parse a `"WxH"` art-size string (e.g. `"1024x768"`) into `(w, h)`. Accepts a
/// lower- or upper-case `x` separator; returns `None` on any malformed/zero input.
pub fn parse_wh(s: &str) -> Option<(u32, u32)> {
    let mut it = s.trim().split(['x', 'X']);
    let w: u32 = it.next()?.trim().parse().ok()?;
    let h: u32 = it.next()?.trim().parse().ok()?;
    if it.next().is_some() || w == 0 || h == 0 {
        return None;
    }
    Some((w, h))
}

impl BuildConfig {
    /// Pixel box `(w, h)` to downscale art into: `max_art_size` (`"WxH"`) if set
    /// and parseable, else the legacy `art_max` as a square bound, else
    /// [`DEFAULT_ART_BOUND`]. Art is fit within the box (aspect kept, never upscaled).
    pub fn art_bounds(&self) -> (u32, u32) {
        if let Some(wh) = self.max_art_size.as_deref().and_then(parse_wh) {
            return wh;
        }
        if let Some(n) = self.art_max {
            return (n, n);
        }
        DEFAULT_ART_BOUND
    }

    /// Whether this build wants colour artwork — true when `art_depths` requests
    /// any depth above 1-bit. A 1-bit-only build (`["1"]`, the Mac Plus / SE
    /// target) is pure black & white: the colour box-art PICTs and the colour
    /// `icl8` icon PICT are skipped, so the image (and the launcher's runtime
    /// memory) shrink to just the 1-bit `.raw` art a compact Mac can use.
    pub fn wants_color_art(&self) -> bool {
        self.art_depths.iter().any(|d| d.trim() != "1")
    }

    /// The launcher memory partition `(preferred_kb, minimum_kb)` to bake in, or
    /// `None` to leave the binary's built-in 2 MB / 1 MB. An explicit `app_mem_kb`
    /// always wins. `minimum` is clamped to be <= `preferred` (the Process Manager
    /// requires it). Deliberately *not* auto-derived from B&W art: a B&W-art build
    /// can still run on a colour screen (paying for the off-screen GWorld), so the
    /// small partition is opted into explicitly for the compact target.
    pub fn effective_app_mem(&self) -> Option<(u32, u32)> {
        self.app_mem_kb.map(|[p, m]| (p, m.min(p)))
    }

    /// The path the launcher MacBinary is read from: [`Self::launcher`] if set, else
    /// `$MACATRIUM_LAUNCHER`, else `build/MacAtrium.bin` (relative to the working dir —
    /// the same convention as `data/templates.json`). It is NOT embedded in this tool.
    pub fn launcher_path(&self) -> PathBuf {
        self.launcher
            .clone()
            .or_else(|| std::env::var_os("MACATRIUM_LAUNCHER").map(PathBuf::from))
            .unwrap_or_else(|| PathBuf::from("build/MacAtrium.bin"))
    }

    /// The launcher MacBinary bytes to install, read from [`Self::launcher_path`].
    /// (The bytes are patched — name, bundle bit, `SIZE` — before injection, so the
    /// on-disk file is never mutated.) A missing file is a clear, actionable error:
    /// build it with Retro68 (`cmake --build build`) or drop a release binary there.
    pub fn launcher_bytes(&self) -> Result<Vec<u8>> {
        let path = self.launcher_path();
        std::fs::read(&path).with_context(|| {
            format!(
                "reading launcher {} — build it with Retro68 (cmake --build build) or \
                 drop a prebuilt MacAtrium.bin there",
                path.display()
            )
        })
    }

    /// The library (dataset) bytes: the file at [`Self::dataset`] if set, otherwise
    /// the [`EMBEDDED_LIBRARY`] — so a build needs no library path.
    pub fn dataset_bytes(&self) -> Result<Vec<u8>> {
        match &self.dataset {
            Some(p) => std::fs::read(p).with_context(|| format!("reading dataset {}", p.display())),
            None => Ok(EMBEDDED_LIBRARY.to_vec()),
        }
    }

    /// The compatibility-overlay bytes: the file at `overrides` (the `compatibility`
    /// key) if set, otherwise the [`EMBEDDED_COMPAT`] — so the requirements/facets
    /// overlay is always applied even when no path is given.
    pub fn compatibility_bytes(&self) -> Result<Vec<u8>> {
        match &self.overrides {
            Some(p) => std::fs::read(p)
                .with_context(|| format!("reading compatibility {}", p.display())),
            None => Ok(EMBEDDED_COMPAT.to_vec()),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fs_id_keeps_short_ids_and_shrinks_long_ones() {
        assert_eq!(fs_id("dark-castle"), "dark-castle"); // short -> unchanged
        let long = "armor-alley-level-editor-2-0"; // 28 chars
        let got = fs_id(long);
        assert!(got.len() <= 17, "fs_id too long: {got} ({})", got.len());
        // longest baked suffix is ".shot.24.pict" (13) -> must fit 31-char HFS.
        assert!(got.len() + ".shot.24.pict".len() <= 31);
        assert_eq!(fs_id(long), got); // deterministic
        assert_ne!(fs_id("a-very-long-game-name-one"), fs_id("a-very-long-game-name-two"));
    }

    #[test]
    fn hfs_name_caps_at_31_and_stays_distinct() {
        assert_eq!(hfs_name("Dark Castle"), "Dark Castle"); // short -> unchanged
        let k31 = "a".repeat(31);
        assert_eq!(hfs_name(&k31), k31); // exactly 31 is kept
        let long = "Where in America's Past Is Carmen Sandiego?";
        let got = hfs_name(long);
        assert_eq!(got.chars().count(), 31, "shortened to the HFS cap");
        assert_eq!(hfs_name(long), got); // deterministic
        // Two long titles HFS would truncate to the same 31 chars stay distinct.
        let a = "Where in America's Past Is Carmen Sandiego";
        let b = "Where in America's Past Is Carmen Sandiego Deluxe Edition";
        assert_ne!(hfs_name(a), hfs_name(b));
        // Char-boundary safe with a multi-byte title (must not panic).
        let _ = hfs_name("A Game\u{2122} With A Very Long Collector's Edition Name");
    }

    #[test]
    fn app_mem_kb_round_trips_and_clamps() {
        // The field both the GUI Save/Load and the `atrium image` CLI rely on.
        let mut c = BuildConfig::default();
        assert_eq!(c.effective_app_mem(), None); // absent -> launcher default

        c.app_mem_kb = Some([COLOR_APP_MEM_KB.0, COLOR_APP_MEM_KB.1]);
        let json = serde_json::to_string(&c).unwrap();
        let back: BuildConfig = serde_json::from_str(&json).unwrap();
        assert_eq!(back.app_mem_kb, Some([1024, 768]));
        assert_eq!(back.effective_app_mem(), Some((1024, 768)));

        // minimum is clamped to <= preferred.
        c.app_mem_kb = Some([512, 999]);
        assert_eq!(c.effective_app_mem(), Some((512, 512)));
    }

    #[test]
    fn omitted_app_mem_kb_deserializes_to_none() {
        // A legacy config without the field must still load (serde default).
        let c: BuildConfig =
            serde_json::from_str(r#"{"out":"o","dataset":"d"}"#).unwrap();
        assert_eq!(c.app_mem_kb, None);
        assert_eq!(c.launcher, None); // launcher is optional -> resolved to a path
    }

    #[test]
    fn disable_control_panels_defaults_on_and_can_be_emptied() {
        // Default: the appliance strips the quick-launch control panels.
        assert_eq!(BuildConfig::default().disable_control_panels, ["Control Strip", "Launcher"]);
        // A config without the field still gets the default (existing builds clean up too).
        let c: BuildConfig = serde_json::from_str(r#"{"out":"o"}"#).unwrap();
        assert_eq!(c.disable_control_panels, ["Control Strip", "Launcher"]);
        // Explicit empty keeps everything.
        let c: BuildConfig = serde_json::from_str(r#"{"out":"o","disable_control_panels":[]}"#).unwrap();
        assert!(c.disable_control_panels.is_empty());
    }

    #[test]
    fn art_depths_default_to_all_three_modes() {
        // Default bakes all three art modes (1/8/24-bit, docs/44) so a build is
        // colour + truecolour, never accidentally B&W-only.
        assert_eq!(BuildConfig::default().art_depths, ["1", "8", "24"]);
        assert!(BuildConfig::default().wants_color_art());
        // A config that omits the field still gets the default (existing builds gain colour).
        let c: BuildConfig = serde_json::from_str(r#"{"out":"o"}"#).unwrap();
        assert_eq!(c.art_depths, ["1", "8", "24"]);
        // An explicit list still wins — e.g. a pure-B&W compact build.
        let c: BuildConfig = serde_json::from_str(r#"{"out":"o","art_depths":["1"]}"#).unwrap();
        assert_eq!(c.art_depths, ["1"]);
        assert!(!c.wants_color_art());
    }

    #[test]
    fn launcher_path_defaults_to_build_dir() {
        // No config path + no env override -> build/MacAtrium.bin (the launcher is
        // never embedded; it's built by Retro68 or dropped in from a release).
        let c = BuildConfig::default();
        assert_eq!(c.launcher_path(), PathBuf::from("build/MacAtrium.bin"));
    }

    #[test]
    fn launcher_path_honors_config() {
        let c: BuildConfig =
            serde_json::from_str(r#"{"out":"o","launcher":"/x/MacAtrium.bin"}"#).unwrap();
        assert_eq!(c.launcher_path(), PathBuf::from("/x/MacAtrium.bin"));
    }

    #[test]
    fn dataset_and_compatibility_default_to_embedded() {
        let c = BuildConfig::default(); // dataset/overrides: None
        assert_eq!(c.dataset_bytes().unwrap(), EMBEDDED_LIBRARY);
        assert_eq!(c.compatibility_bytes().unwrap(), EMBEDDED_COMPAT);
        // sanity: the bundled library is real JSONL, the compat overlay non-empty
        assert!(EMBEDDED_LIBRARY.len() > 1000 && EMBEDDED_LIBRARY.contains(&b'{'));
        assert!(!EMBEDDED_COMPAT.is_empty());
    }

    #[test]
    fn dependencies_loader_skips_doc_key_and_parses_sound_manager() {
        // Parse the bundled registry directly (deterministic — no user overlay).
        let reg = parse_dependencies(EMBEDDED_DEPENDENCIES);
        // The `"//"` documentation key is NOT a dependency and must be skipped, as
        // must any other slash-prefixed key.
        assert!(!reg.contains_key("//"), "the // documentation key leaked in as a dependency");
        assert!(reg.keys().all(|k| !k.starts_with('/')), "a slash-prefixed key survived");
        // The real dependency parses, including its {donor, path} source + install_os.
        let sm = reg.get("sound-manager-3").expect("sound-manager-3 must parse");
        assert_eq!(sm.name, "Sound Manager 3.0");
        assert_eq!(sm.source.donor, "macgarden");
        assert_eq!(sm.source.path, "/MacAtrium/_deps/sound-manager-3");
        assert_eq!(sm.install_os, ["7.1"]);
        // The placeholder entry parses too, with an empty (no-op) install_os.
        assert!(reg.get("quicktime").expect("quicktime placeholder present").install_os.is_empty());
    }
}

impl Default for BuildConfig {
    fn default() -> Self {
        BuildConfig {
            system: None,
            base_os: None,
            out: PathBuf::new(),
            launcher: None,
            dataset: None,
            disk_size_mb: None,
            selection: None,
            collection: None,
            startup_items: d_startup(),
            overrides: None,
            metadata: None,
            mg_archive: None,
            platform: d_platform(),
            detect_color: false,
            curl: d_curl(),
            harvest: Vec::new(),
            art_dir: None,
            art_depth: d_artdepth(),
            art_depths: d_art_depths(),
            art_forks: d_art_forks(),
            art_max: None,
            max_art_size: None,
            download_art: false,
            rb_cli: d_rbcli(),
            apps_root: d_apps_root(),
            metadata_dir: d_metadir(),
            images_dir: d_imagesdir(),
            stage: None,
            startup_sound: None,
            shutdown_sound: None,
            rebuild_desktop: d_rebuild_desktop(),
            snow_harness: None,
            snow_rom: None,
            snow_mdc_rom: None,
            right_size: d_right_size(),
            free_space_pct: d_free_space_pct(),
            free_space_min_mb: d_free_space_min_mb(),
            sounds_dir: d_sounds_dir(),
            finder_replace: false,
            install_all_systems: false,
            app_mem_kb: None,
            disable_control_panels: d_disable_cdevs(),
        }
    }
}
