/*
 * ui.c — see ui.h. Direct-to-window drawing; full redraw per change (MVP).
 */
#include "ui.h"
#include "art.h"
#include "display.h"
#include "sound.h"
#include "mac_compat.h"
#include "version.h"   /* MACATRIUM_VERSION — git build stamp (generated by CMake) */

#include <string.h>

#define HEADER_H 30
#define HINT_H   24
#define MARGIN   10
#define ROW_H    18
#define NARROW_W 420
#define ICON_SZ  16            /* list-row icon box (px); 32x32 art fits into it */
#define ICON_GUT 22            /* icon column width incl. the gap before the name */
#define CATLIST_W 140          /* width of the optional categories list panel (left) */

/* Esc-menu row kinds and their labels (indexed by kind). The visible set per run
 * is built into Ui::menuRows by ui_init (Finder rows omitted on the boot shell). */
enum { MROW_SETTINGS, MROW_SHOW_FINDER, MROW_EXIT, MROW_RESTART, MROW_SHUTDOWN };
static const char *kMenuLabel[] = { "Settings", "Show Finder", "Exit to Finder", "Restart", "Shut Down" };

/* ---- small helpers -------------------------------------------------------- */

static void l2s(long v, char *buf)               /* long -> C string */
{
    char tmp[16];
    int  n = 0, i = 0;
    int  neg = (v < 0);
    unsigned long u = neg ? (unsigned long)(-v) : (unsigned long)v;
    if (u == 0) tmp[n++] = '0';
    while (u) { tmp[n++] = (char)('0' + (u % 10)); u /= 10; }
    if (neg) tmp[n++] = '-';
    while (n) buf[i++] = tmp[--n];
    buf[i] = '\0';
}

static int win_w(Ui *u) { return u->win->portRect.right - u->win->portRect.left; }
static int win_h(Ui *u) { return u->win->portRect.bottom - u->win->portRect.top; }

/* "1991 - Psygnosis - Puzzle, Strategy" from the item's display fields. ASCII
 * separators only — the launcher renders MacRoman, so we avoid non-ASCII glyphs.
 * `out` must hold >= ITEM_VENDOR_LEN + ITEM_GENRE_LEN + 32 bytes. */
static void build_meta(const CatItem *it, char *out)
{
    char num[16];
    out[0] = '\0';
    if (it->year > 0) { l2s(it->year, num); strcat(out, num); }
    if (it->vendor[0]) { if (out[0]) strcat(out, " - "); strcat(out, it->vendor); }
    if (it->genre[0])  { if (out[0]) strcat(out, " - "); strcat(out, it->genre); }
}

/* Word-wrap `s` into `maxw` px, drawing each line from baseline `y` stepping by
 * `dy`, up to `maxlines`. Returns the baseline after the last line drawn. */
static short draw_wrapped(Render *r, short x, short y, short maxw, short dy,
                          const char *s, int ink, int maxlines)
{
    char line[200], cand[200], word[80];
    int  ll = 0, lines = 0, i = 0;
    while (s[i] && lines < maxlines) {
        int wl = 0, cl = 0;
        while (s[i] == ' ') i++;                       /* skip run of spaces */
        while (s[i] && s[i] != ' ' && wl < (int)sizeof word - 1) word[wl++] = s[i++];
        word[wl] = '\0';
        if (wl == 0) break;
        if (ll > 0) { memcpy(cand, line, ll); cl = ll; cand[cl++] = ' '; }
        memcpy(cand + cl, word, wl); cl += wl; cand[cl] = '\0';
        if (ll > 0 && render_text_width(r, cand) > maxw) {
            line[ll] = '\0';
            render_text(r, x, y, line, ink);
            y = (short)(y + dy); lines++;
            memcpy(line, word, wl); ll = wl; line[ll] = '\0';
        } else {
            memcpy(line, cand, cl); ll = cl; line[ll] = '\0';
        }
    }
    if (ll > 0 && lines < maxlines) {
        line[ll] = '\0';
        render_text(r, x, y, line, ink);
        y = (short)(y + dy);
    }
    return y;
}

/* keep the selected row within the visible window */
static int clamp_scroll(Ui *u, int visRows)
{
    ModelCat *c = model_cur_cat(u->m);
    if (!c || c->count == 0) { u->m->topRow = 0; return 0; }
    if (visRows < 1) visRows = 1;
    if (u->m->curItem < u->m->topRow)
        u->m->topRow = u->m->curItem;
    else if (u->m->curItem >= u->m->topRow + visRows)
        u->m->topRow = u->m->curItem - visRows + 1;
    if (u->m->topRow < 0) u->m->topRow = 0;
    return u->m->topRow;
}

/* ---- public --------------------------------------------------------------- */

void ui_init(Ui *u, Env *env, Render *r, Model *m, WindowPtr win, int safe)
{
    u->env = env; u->r = r; u->m = m; u->win = win;
    u->mode = UI_MODE_LIST;
    u->menuSel = 0;
    u->safe = safe;
    u->status[0] = '\0';
    u->previewPic = 0;
    u->listArt = 0;
    u->artFor = 0;
    u->settingsFocus = 0;
    u->setSel = 0;
    u->ndepths = display_depths(u->depths, UI_MAX_DEPTHS);   /* all OS-supported depths */
    u->vol = sound_available() ? sound_get_vol() : -1;
    u->artPref = 1;                            /* Screenshot is the primary cover (box art on P) */
    u->view = VIEW_CAROUSEL;                   /* default browse view (first-run chooser may change) */
    u->setupSel = 0;
    u->carousel = 7;                           /* icons shown: 7 by default (odd 3..25), fit-capped */
    u->sndStartup = 0;                                       /* sounds off by default */
    u->sndShutdown = 0;
    u->ncdevs = 0; u->cdevSel = 0; u->cdevTop = 0;           /* control-panel list */
    u->bgValid = 0;                                          /* force a full first paint */
    u->lastMode = -1;
    u->overlayDrawn = 0; u->lastSel = -1;                    /* overlay partial-redraw state */
    u->catList = 0;                                          /* categories list hidden */
    {
        int i;
        for (i = 0; i < MAX_ITEMS; i++) u->rowIcon[i] = 0;   /* lazy row-icon cache */
    }
    /* Build the Esc menu for this environment. "Show Finder" / "Exit to Finder"
     * only make sense when a separate Finder process exists to front or hand back
     * to — true on System 7 (we're a Startup Item) or System 6 + MultiFinder. On
     * the System-6 boot-shell build the launcher replaced the Finder, so those
     * rows are dropped (canLaunchReturn is false: no Process Manager / Finder). */
    {
        int k = 0;
        u->menuRows[k++] = MROW_SETTINGS;
        if (env->canLaunchReturn) {
            u->menuRows[k++] = MROW_SHOW_FINDER;
            u->menuRows[k++] = MROW_EXIT;
        }
        u->menuRows[k++] = MROW_RESTART;
        u->menuRows[k++] = MROW_SHUTDOWN;
        u->nmenu = k;
    }
}

/* The art base path for an item's main cover. Screenshot (`shot`) is the primary
 * cover by default (artPref==1); the Artwork setting can flip the main pane to
 * box art (`image`). Each falls back to the other so a pane is never needlessly
 * empty. Box art is always reachable full-screen via the P key regardless. */
static const char *art_base(Ui *u, const CatItem *it)
{
    if (u->artPref == 1) return it->shot[0] ? it->shot : it->image;
    return it->image[0] ? it->image : it->shot;
}

void ui_set_status(Ui *u, const char *msg)
{
    strncpy(u->status, msg, sizeof u->status - 1);
    u->status[sizeof u->status - 1] = '\0';
}

const char *ui_current_app(Ui *u)
{
    const CatItem *it = model_cur_item(u->m);
    return it ? it->app : 0;
}

const char *ui_current_name(Ui *u)
{
    const CatItem *it = model_cur_item(u->m);
    return it ? it->name : 0;
}

/* Per-game max colour depth (bpp) from the catalog; 0 = no cap. */
int ui_current_maxdepth(Ui *u)
{
    const CatItem *it = model_cur_item(u->m);
    return it ? it->maxDepth : 0;
}

const CtlPanel *ui_current_cdev(Ui *u)
{
    if (u->cdevSel < 0 || u->cdevSel >= u->ncdevs) return 0;
    return &u->cdevs[u->cdevSel];
}

/* ---- drawing -------------------------------------------------------------- */

static Art *load_item_art(Ui *u, const char *image);   /* defined below */

/* Load the current selection's detail art if it isn't already loaded for that
 * item. Returns 1 if it (re)loaded, 0 if already current. Drives both the
 * deferred path (ui_idle, so a fast scroll on the direct-draw System-6 build
 * doesn't lurch on each PICT decode) and the synchronous path (draw_carousel on
 * the off-screen System-7 build, so the cover appears in the same repaint as the
 * move instead of flashing in on a second pass). */
static int ensure_art_loaded(Ui *u)
{
    const CatItem *cur = model_cur_item(u->m);
    if (cur == u->artFor) return 0;            /* already loaded for this item */
    if (u->listArt) { art_dispose(u->listArt); u->listArt = 0; }
    if (cur) {
        const char *base = art_base(u, cur);
        if (base && base[0]) u->listArt = load_item_art(u, base);
    }
    u->artFor = cur;
    return 1;
}

/* The small list-row icon for catalog item `catIdx`, lazily loaded and cached
 * (depth-matched like art: 1-bit ICN# .raw, or the icl8 .8.pict on colour
 * screens). NULL if the item has no icon or it won't load. */
static Art *row_icon(Ui *u, int catIdx, const CatItem *it)
{
    if (catIdx < 0 || catIdx >= MAX_ITEMS) return 0;
    if (!u->rowIcon[catIdx] && it->icon[0])
        u->rowIcon[catIdx] = load_item_art(u, it->icon);
    return u->rowIcon[catIdx];
}

/* Drop every cached row icon (e.g. after a depth change — the icl8 colour
 * variant differs from the 1-bit one). */
static void dispose_row_icons(Ui *u)
{
    int i;
    for (i = 0; i < MAX_ITEMS; i++)
        if (u->rowIcon[i]) { art_dispose(u->rowIcon[i]); u->rowIcon[i] = 0; }
}

/* Invalidate the per-item art caches after a category page loads. The paged
 * catalog reuses one items array for every category (main.c), so both caches
 * alias the *previous* page's items by reused storage: `artFor` is a CatItem*
 * (now pointing at a different title at the same address) and `rowIcon[]` is
 * keyed by the reused slot index. Without this, a new selection that lands on a
 * slot the old page also used keeps the previous item's cover / tile icon.
 * Called by main's PageLoader right after model_set_page. */
void ui_page_changed(Ui *u)
{
    if (u->listArt) { art_dispose(u->listArt); u->listArt = 0; }
    u->artFor = 0;
    dispose_row_icons(u);
}

#define ART_PANE_W 176          /* right-hand art pane width when wide enough */
#define ART_MIN_W  560          /* show the art pane only at this width or more */

/* Art-pane width: the classic 176 px up to 720 px wide (640x480 unchanged), then
 * a proportional ~27% (capped at 360) on bigger screens so the art isn't a sliver
 * at 800x600 / 1024x768. The list takes the rest of the width. */
static int art_pane_w(int W)
{
    int w;
    if (W <= 720) return ART_PANE_W;
    w = W * 27 / 100;
    if (w < ART_PANE_W) w = ART_PANE_W;
    if (w > 360) w = 360;
    return w;
}

#define GEAR_X 8                /* settings affordance: left edge */
#define GEAR_W 24               /* ...and reserved width (title starts after) */

/* Mouse affordances on the browse screen (docs/07): the carousel ◀▶ arrows and
 * the Launch button below the selected icon. Sizes are fixed so hit-testing in
 * ui_click() needs no font metrics (which aren't reliable outside a draw pass). */
#define ARROW_W  26
#define ARROW_H  28
#define LAUNCH_W 84
#define LAUNCH_H 22
#define CATBAND_HALF 80         /* clickable half-width of the centred "^ cat v" */

/* The Settings affordance at the header's left — a little 3-slider icon. A frame
 * around it shows it's focused (reached by pressing Left at the first category;
 * Enter then opens the Settings panel). */
static void draw_settings_btn(Ui *u)
{
    Render *r = u->r;
    Rect    box, knob;
    short   x0 = GEAR_X, x1 = (short)(GEAR_X + 14);
    render_hline(r, x0, x1, 10);
    render_hline(r, x0, x1, 15);
    render_hline(r, x0, x1, 20);
    SetRect(&knob, (short)(x0 + 9), 8,  (short)(x0 + 12), 12); render_frame(r, &knob);
    SetRect(&knob, (short)(x0 + 3), 13, (short)(x0 + 6),  17); render_frame(r, &knob);
    SetRect(&knob, (short)(x0 + 8), 18, (short)(x0 + 11), 22); render_frame(r, &knob);
    if (u->settingsFocus) {
        SetRect(&box, (short)(GEAR_X - 4), 3, (short)(GEAR_X + GEAR_W - 4), (short)(HEADER_H - 4));
        render_frame(r, &box);
    }
}

static void draw_safe(Ui *u)
{
    Render *r = u->r;
    Rect full = u->win->portRect;
    int W = win_w(u), H = win_h(u);
    short cy = (short)(H / 2 - 30);

    render_fill(r, &full, FILL_BG);

    render_text_size(r, 12);
    {
        const char *t = "MacAtrium";
        short x = (short)((W - render_text_width(r, t)) / 2);
        render_text(r, x, (short)(cy - 24), t, INK_TITLE);
    }
    {
        const char *t = "No catalog found.";
        short x = (short)((W - render_text_width(r, t)) / 2);
        render_text(r, x, cy, t, INK_NORMAL);
    }
    {
        const char *t = "Expected: /MacAtrium/metadata/catalog.jsonl";
        short x = (short)((W - render_text_width(r, t)) / 2);
        render_text(r, x, (short)(cy + 22), t, INK_DIM);
    }
    {
        const char *t = "Press Esc for Restart / Shut Down.";
        short x = (short)((W - render_text_width(r, t)) / 2);
        render_text(r, x, (short)(cy + 50), t, INK_NORMAL);
    }
}

/* Draw one carousel tile: the item's app icon (depth-matched, cached) centered
 * at (cx, cy) in an sz x sz box, or a framed placeholder if it has no icon. */
static void draw_tile(Ui *u, int catIdx, const CatItem *it, short cx, short cy, short sz)
{
    Rect box;
    Art *ic;
    short h = (short)(sz / 2);
    SetRect(&box, (short)(cx - h), (short)(cy - h), (short)(cx + h), (short)(cy + h));
    ic = it->icon[0] ? row_icon(u, catIdx, it) : 0;
    if (ic) art_draw_fit(ic, &box);
    else    render_frame(u->r, &box);          /* icon-less item placeholder */
}

/* The browse screen: a horizontal icon carousel (Left/Right scroll the games,
 * the selected one enlarged in the centre; Up/Down change category) over a
 * detail panel (the selected game's art + name / developer / genre / blurb).
 * Reuses the lazily-cached app icons (carousel) and the depth-matched art
 * loader (detail pane), so a move is mostly cheap icon blits. */
/* Browse-screen geometry, computed once and shared by draw_carousel() (drawing)
 * and ui_click() (hit-testing) so the drawn pixels and the clickable rects can
 * never drift apart. Holds the band rects, the centre/side tile metrics, and the
 * mouse-control rects (gear, category band, the ◀▶ arrows, the Launch button). */
typedef struct {
    int   W, H;
    short clx;                       /* content left edge (cat list or 0)        */
    short carTop, carBot, detTop, detBot;
    int   hasItems, count, center;
    short cx, iconCy, centSz, half, sideSz, sideGap;
    int   nside;
    Rect  gear, catBand, leftArrow, rightArrow, launchBtn;
    short catMidX;                   /* split: click < = prev cat, >= = next cat */
} CarLayout;

static void carousel_layout(Ui *u, CarLayout *L)
{
    int       W = win_w(u), H = win_h(u);
    ModelCat *cat = model_cur_cat(u->m);
    int       usable = H - HEADER_H - HINT_H;
    int       carH   = usable * 42 / 100;
    if (carH < 120) carH = 120;

    L->W = W; L->H = H;
    L->clx    = (short)(u->catList ? CATLIST_W : 0);
    L->carTop = HEADER_H;
    L->carBot = (short)(HEADER_H + carH);
    L->detTop = (short)(L->carBot + 1);
    L->detBot = (short)(H - HINT_H);
    L->count  = cat ? cat->count : 0;
    L->center = u->m->curItem;
    L->hasItems = (cat && cat->count > 0);

    SetRect(&L->gear, (short)(GEAR_X - 4), 3,
            (short)(GEAR_X + GEAR_W - 4), (short)(HEADER_H - 4));
    L->catMidX = (short)(W / 2);
    SetRect(&L->catBand, (short)(W / 2 - CATBAND_HALF), 2,
            (short)(W / 2 + CATBAND_HALF), (short)(HEADER_H - 2));

    SetRect(&L->leftArrow,  0, 0, 0, 0);
    SetRect(&L->rightArrow, 0, 0, 0, 0);
    SetRect(&L->launchBtn,  0, 0, 0, 0);
    L->cx = L->iconCy = L->centSz = L->half = L->sideSz = 0;
    L->sideGap = 8; L->nside = 0;

    if (L->hasItems) {
        short cx     = (short)((L->clx + W) / 2);
        short iconCy = (short)(L->carTop + (carH - 22) / 2);
        short centSz = (short)(carH - 44);
        short sideSz, half, top;
        int   nside;
        if (centSz > 76) centSz = 76;
        if (centSz < 40) centSz = 40;
        sideSz = (short)(centSz * 9 / 16);
        half   = (short)(centSz / 2);
        /* leave room for an arrow button at each edge so tiles never sit under it */
        nside  = ((W - L->clx) / 2 - half - MARGIN - ARROW_W) / (sideSz + L->sideGap);
        {   /* user cap: `carousel` is an odd icon count 3..25 -> 1..12 per side. The
             * fit formula above already scales nside down to the screen width, so the
             * effective count is min(fits, user) and auto-grows on bigger screens. */
            int maxSide = (u->carousel - 1) / 2;
            if (maxSide < 1)  maxSide = 1;
            if (maxSide > 12) maxSide = 12;
            if (nside > maxSide) nside = maxSide;
        }
        if (nside < 1) nside = 1;

        L->cx = cx; L->iconCy = iconCy; L->centSz = centSz;
        L->half = half; L->sideSz = sideSz; L->nside = nside;

        SetRect(&L->leftArrow,  (short)(L->clx + MARGIN), (short)(iconCy - ARROW_H / 2),
                (short)(L->clx + MARGIN + ARROW_W), (short)(iconCy + ARROW_H / 2));
        SetRect(&L->rightArrow, (short)(W - MARGIN - ARROW_W), (short)(iconCy - ARROW_H / 2),
                (short)(W - MARGIN), (short)(iconCy + ARROW_H / 2));
        top = (short)(iconCy + half + 6);
        SetRect(&L->launchBtn, (short)(cx - LAUNCH_W / 2), top,
                (short)(cx + LAUNCH_W / 2), (short)(top + LAUNCH_H));
    }
}

/* The framed detail-cover rect, from the shared layout — so draw_carousel and the
 * targeted ui_draw_art agree on where the cover goes. */
static void detail_art_rect(const CarLayout *L, Rect *ar)
{
    short artW = (short)((L->W - L->clx) * 2 / 5);
    if (artW > 220) artW = 220;
    SetRect(ar, (short)(L->clx + MARGIN), (short)(L->detTop + MARGIN),
            (short)(L->clx + MARGIN + artW), (short)(L->detBot - MARGIN));
}

/* Paint the detail cover into its box: clear (so a targeted refresh erases the
 * previous item's art), frame, then the loaded cover — or "(no art)" once a load
 * for this item found nothing; empty until the cover has loaded. */
static void draw_detail_art(Ui *u, const Rect *ar)
{
    Render        *r      = u->r;
    const CatItem *cur    = model_cur_item(u->m);
    int            loaded = (cur && cur == u->artFor);
    render_fill(r, ar, FILL_BG);
    render_frame(r, ar);
    if (loaded && u->listArt) {
        Rect inner = *ar;
        InsetRect(&inner, 4, 4);
        art_draw_fit(u->listArt, &inner);
    } else if (loaded) {
        const char *t = "(no art)";
        render_text(r, (short)(ar->left + ((ar->right - ar->left) - render_text_width(r, t)) / 2),
                    (short)((ar->top + ar->bottom) / 2), t, INK_DIM);
    }
}

static void draw_carousel(Ui *u)
{
    Render        *r   = u->r;
    Model         *m   = u->m;
    ModelCat      *cat = model_cur_cat(m);
    const CatItem *cur = model_cur_item(m);
    Rect           full = u->win->portRect;
    char           num[16];
    CarLayout      L;
    int            W, H;
    short          clx, carTop, carBot, detTop, detBot;

    carousel_layout(u, &L);
    W = L.W; H = L.H; clx = L.clx;
    carTop = L.carTop; carBot = L.carBot; detTop = L.detTop; detBot = L.detBot;

    render_fill(r, &full, FILL_BG);

    /* ---- optional categories list (left panel) ---- */
    if (u->catList) {
        short sy = HEADER_H, sb = (short)(H - HINT_H);
        int   rows = (sb - sy - 4) / ROW_H;
        int   top, i;
        Rect  sr;
        SetRect(&sr, 0, sy, CATLIST_W, sb);
        render_fill(r, &sr, FILL_PANEL);
        render_frame(r, &sr);
        top = m->curCat - rows / 2;
        if (top + rows > m->ncats) top = m->ncats - rows;
        if (top < 0) top = 0;
        for (i = 0; i < rows; i++) {
            int   ci = top + i;
            short y0 = (short)(sy + 2 + i * ROW_H), base = (short)(y0 + ROW_H - 5);
            int   sel;
            char  nm[ITEM_CAT_LEN];
            if (ci >= m->ncats) break;
            sel = (ci == m->curCat);
            SetRect(&sr, 2, y0, (short)(CATLIST_W - 2), (short)(y0 + ROW_H));
            render_fill(r, &sr, sel ? FILL_SEL : FILL_PANEL);
            strncpy(nm, m->cats[ci].name, sizeof nm - 1); nm[sizeof nm - 1] = '\0';
            while (nm[0] && render_text_width(r, nm) > CATLIST_W - 14) nm[strlen(nm) - 1] = '\0';
            render_text(r, 8, base, nm, sel ? INK_SELECTED : INK_NORMAL);
        }
    }

    /* Off-screen (System 7+) path: load the selected cover *now* so it lands in
     * this same repaint as the move — no deferred second pass that flashes it in.
     * Cheap: the compositing GWorld blits once and the size-capped PICTs decode
     * fast. The direct-draw System-6 path skips this and keeps the deferred load
     * (ui_idle) so a fast scroll there never lurches on a per-move PICT decode;
     * its detail pane just stays empty until the selection settles. */
    if (u->r->useOffscreen) ensure_art_loaded(u);

    /* ---- header: gear, the category (with ^v), and N / M (the app title now
     * lives in the System menu bar, so it's no longer repeated here) ---- */
    render_text_size(r, 12);
    draw_settings_btn(u);
    if (cat) {
        char  cl[ITEM_CAT_LEN + 8];
        short cw;
        strcpy(cl, "^ "); strcat(cl, cat->name); strcat(cl, " v");
        cw = render_text_width(r, cl);
        render_text(r, (short)((W - cw) / 2), 20, cl, INK_NORMAL);
        {
            char line[24];
            l2s(m->curItem + 1, num); strcpy(line, num);
            strcat(line, " / ");
            l2s(cat->count, num); strcat(line, num);
            render_text(r, (short)(W - MARGIN - render_text_width(r, line)), 20, line, INK_DIM);
        }
    }
    render_hline(r, 0, (short)W, (short)(HEADER_H - 1));

    /* ---- carousel band (in the content area to the right of any cat list) ---- */
    if (!cat || cat->count == 0) {
        const char *t = "(no items in this category)";
        render_text(r, (short)(clx + (W - clx - render_text_width(r, t)) / 2),
                    (short)((carTop + carBot) / 2), t, INK_DIM);
    } else {
        int   center  = L.center;
        short cx      = L.cx;
        short iconCy  = L.iconCy;
        short centSz  = L.centSz;
        short sideSz  = L.sideSz, sideGap = L.sideGap, half = L.half;
        int   nside   = L.nside, k;

        /* side tiles, WRAPPING so the carousel always looks full and continuous:
         * the slots before the first item show the category's LAST items (and
         * vice versa), so the default view reads as a carousel you can scroll
         * either way. A `seen` guard stops a small category (fewer items than
         * slots) from drawing the same item twice. Inner slots fill first. */
        {
            char seen[MAX_CAT_ITEMS];
            int  cnt = cat->count;
            memset(seen, 0, sizeof seen);
            if (center >= 0 && center < cnt) seen[center] = 1;
            for (k = 1; k <= nside; k++) {
                short off = (short)(half + sideGap + sideSz / 2 + (k - 1) * (sideSz + sideGap));
                int   li  = ((center - k) % cnt + cnt) % cnt;
                int   ri  = (center + k) % cnt;
                if (!seen[li]) {
                    seen[li] = 1;
                    draw_tile(u, cat->idx[li], &m->cat->items[cat->idx[li]],
                              (short)(cx - off), iconCy, sideSz);
                }
                if (!seen[ri]) {
                    seen[ri] = 1;
                    draw_tile(u, cat->idx[ri], &m->cat->items[cat->idx[ri]],
                              (short)(cx + off), iconCy, sideSz);
                }
            }
        }
        /* centre tile: ALWAYS the app's own icon at the current screen depth — it
         * never swaps to the box art. The hero cover lives only in the detail pane
         * below; drawing it here too made the centre flip icon->cover when ui_idle
         * finished loading (and, on the direct-draw 6.0.8 path, painted the cover
         * twice per repaint — the "multiple passes"). A stable icon column avoids
         * both. */
        draw_tile(u, cat->idx[center], cur, cx, iconCy, centSz);
        {   /* 2px square selection box around the centred (selected) icon */
            Rect f;
            short pad = (short)(half + 5);
            SetRect(&f, (short)(cx - pad), (short)(iconCy - pad),
                    (short)(cx + pad), (short)(iconCy + pad));
            render_frame(r, &f);
            InsetRect(&f, 1, 1);
            render_frame(r, &f);
        }
        /* ◀▶ navigation arrows flanking the carousel. Both stay active because the
         * carousel wraps (there's always somewhere to scroll); dim only a 1-item
         * category, where there's nothing to move to. */
        {
            short tw;
            short ink = cat->count > 1 ? INK_NORMAL : INK_DIM;
            render_frame(r, &L.leftArrow);
            tw = render_text_width(r, "<");
            render_text(r, (short)(L.leftArrow.left + (ARROW_W - tw) / 2),
                        (short)(iconCy + 5), "<", ink);
            render_frame(r, &L.rightArrow);
            tw = render_text_width(r, ">");
            render_text(r, (short)(L.rightArrow.left + (ARROW_W - tw) / 2),
                        (short)(iconCy + 5), ">", ink);
        }
        /* Launch button directly below the selected icon */
        {
            short tw = render_text_width(r, "Launch");
            render_fill(r, &L.launchBtn, FILL_SEL);
            render_frame(r, &L.launchBtn);
            render_text(r, (short)(L.launchBtn.left + (LAUNCH_W - tw) / 2),
                        (short)(L.launchBtn.top + LAUNCH_H - 6), "Launch", INK_SELECTED);
        }
        if (cur) {
            short nw = render_text_width(r, cur->name);
            render_text(r, (short)(clx + (W - clx - nw) / 2), (short)(carBot - 6),
                        cur->name, INK_TITLE);
        }
    }
    render_hline(r, clx, (short)W, carBot);

    /* ---- detail band: art (left) + name / meta / blurb (right) ---- */
    {
        /* Cover is loaded synchronously above (off-screen path) or by ui_idle once
         * the selection settles (direct-draw path); on that path the deferred load
         * repaints ONLY this cover box (ui_draw_art), not the whole screen. */
        Rect ar;
        detail_art_rect(&L, &ar);
        draw_detail_art(u, &ar);
        if (cur) {
            short tx   = (short)(ar.right + 2 * MARGIN);
            short ty   = (short)(detTop + 18);
            short maxw = (short)(W - tx - MARGIN);
            char  buf[ITEM_VENDOR_LEN + 24];

            /* title */
            render_text(r, tx, ty, cur->name, INK_TITLE);
            ty = (short)(ty + ROW_H + 3);

            /* year - developer */
            buf[0] = '\0';
            if (cur->year > 0) { l2s(cur->year, num); strcat(buf, num); }
            if (cur->vendor[0]) {
                if (buf[0]) strcat(buf, " - ");
                strncat(buf, cur->vendor, sizeof buf - strlen(buf) - 1);
            }
            if (buf[0]) { render_text(r, tx, ty, buf, INK_DIM); ty = (short)(ty + ROW_H); }

            /* genre on its own line */
            if (cur->genre[0]) {
                char g[ITEM_GENRE_LEN + 8];
                strcpy(g, "Genre: ");
                strncat(g, cur->genre, ITEM_GENRE_LEN);
                render_text(r, tx, ty, g, INK_DIM);
                ty = (short)(ty + ROW_H);
            }
            ty = (short)(ty + 6);

            /* description (a transient status line wins) */
            if (u->status[0])
                render_text(r, tx, ty, u->status, INK_NORMAL);
            else if (cur->desc[0])
                draw_wrapped(r, tx, ty, maxw, ROW_H, cur->desc, INK_NORMAL, 7);

            /* tags: the navigational categories, along the panel's last line */
            if (cur->ncats > 0) {
                char tags[ITEM_CAT_LEN * 5];
                int  ci;
                tags[0] = '\0';
                for (ci = 0; ci < cur->ncats; ci++) {
                    if (strlen(tags) + strlen(cur->cats[ci]) + 4 >= sizeof tags) break;
                    if (tags[0]) strcat(tags, " - ");
                    strcat(tags, cur->cats[ci]);
                }
                if (tags[0]) render_text(r, tx, (short)(detBot - 8), tags, INK_DIM);
            }
        }
    }

    /* ---- hint bar ---- */
    render_hline(r, 0, (short)W, (short)(H - HINT_H));
    {
        const char *hint = u->settingsFocus
            ? "Settings:   Return  open       v  back"
            : "<- ->  game    ^ v  category    Return  play    I  info   P  box art   Esc  menu";
        short x = (short)((W - render_text_width(r, hint)) / 2);
        if (x < MARGIN) x = MARGIN;
        render_text(r, x, (short)(H - 7), hint, INK_DIM);
    }
}

/* The Settings panel: a list of adjustable rows (Theme / Color Depth / Volume /
 * Artwork / Startup Sound / Shutdown Sound) plus a Control Panels action row.
 * Up/Down move rows; Left/Right (and Return) change the selected row's value;
 * Return on the last row opens the Control Panels list. */
/* Browse-view display names (Settings "View" row + the first-run chooser) and
 * one-line descriptions (chooser only). Defined here so set_row_text can name the
 * current view; draw_setup (further down) reuses them. */
static const char *kViewName[VIEW_N] = { "Carousel", "Icon Grid", "List Browser" };
static const char *kViewDesc[VIEW_N] = {
    "Flip through big covers. Best for keyboard / controller.",
    "A grid of icons, like the Finder. Good with a mouse.",
    "Categories + a list with screenshots. Best for big libraries."
};

#define SET_N 10
#define SET_ROW_VIEW      6             /* browse view: Carousel / Icon / List      */
#define SET_ROW_CTLPANELS (SET_N - 1)   /* the action row (opens the cdev list)     */

static void set_row_text(Ui *u, int row, char *out)
{
    char num[16];
    switch (row) {
        case 0:
            strcpy(out, "Theme");
            while (strlen(out) < 16) strcat(out, " ");
            strcat(out, (u->r->theme == THEME_LIGHT) ? "Light" : "Dark");
            break;
        case 1:
            strcpy(out, "Color Depth");
            while (strlen(out) < 16) strcat(out, " ");
            if      (u->env->pixelSize >= 32) { strcat(out, "Millions"); }
            else if (u->env->pixelSize >= 16) { strcat(out, "Thousands"); }
            else { l2s(u->env->pixelSize, num); strcat(out, num); strcat(out, "-bit"); }
            break;
        case 2:
            strcpy(out, "Volume");
            while (strlen(out) < 16) strcat(out, " ");
            if (u->vol < 0) { strcat(out, "n/a"); }
            else { l2s(u->vol, num); strcat(out, num); strcat(out, " / 7"); }
            break;
        case 3:
            strcpy(out, "Artwork");
            while (strlen(out) < 16) strcat(out, " ");
            strcat(out, (u->artPref == 1) ? "Screenshot" : "Box Art");
            break;
        case 4:
            strcpy(out, "Startup Sound");
            while (strlen(out) < 16) strcat(out, " ");
            strcat(out, u->sndStartup ? "On" : "Off");
            break;
        case 5:
            strcpy(out, "Shutdown Sound");
            while (strlen(out) < 16) strcat(out, " ");
            strcat(out, u->sndShutdown ? "On" : "Off");
            break;
        case 6:
            strcpy(out, "View");
            while (strlen(out) < 16) strcat(out, " ");
            strcat(out, kViewName[(u->view >= 0 && u->view < VIEW_N) ? u->view : 0]);
            break;
        case 7:
            strcpy(out, "Categories");
            while (strlen(out) < 16) strcat(out, " ");
            strcat(out, u->catList ? "Shown" : "Hidden");
            break;
        case 8:
            strcpy(out, "Carousel");
            while (strlen(out) < 16) strcat(out, " ");
            l2s(u->carousel, num); strcat(out, num); strcat(out, " icons");
            break;
        default:
            strcpy(out, "Control Panels");
            while (strlen(out) < 16) strcat(out, " ");
            strcat(out, "Open >");
            break;
    }
}

/* One Settings row (selection highlight + "Label   value" text). Shared by the
 * full-panel draw and the partial (selection/value-changed) redraw, so adjusting a
 * row repaints just that row instead of re-filling — and flashing — the whole panel
 * (mirrors draw_menu_row, which already gives the Esc menu a clean refresh). */
static void draw_settings_row(Ui *u, short px, short py, int pw, int i)
{
    Render *r = u->r;
    short   y0   = (short)(py + 40 + i * (ROW_H + 6));
    short   base = (short)(y0 + ROW_H - 5);
    int     sel  = (i == u->setSel);
    char    line[48];
    Rect    rr;
    SetRect(&rr, (short)(px + 4), y0, (short)(px + pw - 4), (short)(y0 + ROW_H));
    render_fill(r, &rr, sel ? FILL_SEL : FILL_PANEL);
    set_row_text(u, i, line);
    render_text(r, (short)(px + MARGIN), base, line, sel ? INK_SELECTED : INK_NORMAL);
}

/* The contextual bottom hint (clip-length note on the sound rows, the open hint on
 * Control Panels, else the nav keys). Depends on the selected row, so it's redrawn
 * on every selection move; clears its band first so the previous hint doesn't ghost. */
static void draw_settings_hint(Ui *u, short px, short py, int pw, int ph)
{
    Render     *r = u->r;
    const char *hint;
    Rect        band;
    short       x;
    SetRect(&band, (short)(px + 1), (short)(py + ph - 21),
            (short)(px + pw - 1), (short)(py + ph - 1));
    render_fill(r, &band, FILL_PANEL);
    if (u->setSel == 4 || u->setSel == 5)
        hint = "Sounds: a clip baked in the image, max 7 sec";
    else if (u->setSel == SET_ROW_CTLPANELS)
        hint = "Return  open the Control Panels list";
    else
        hint = "^v row   <> change   Esc back";
    x = (short)(px + (pw - render_text_width(r, hint)) / 2);
    if (x < (short)(px + 4)) x = (short)(px + 4);
    render_text(r, x, (short)(py + ph - 7), hint, INK_DIM);
}

static void draw_settings(Ui *u)
{
    Render *r = u->r;
    int     W = win_w(u), H = win_h(u);
    int     pw = 320;
    int     ph = SET_N * (ROW_H + 6) + 56;
    short   px = (short)((W - pw) / 2);
    short   py = (short)((H - ph) / 2);
    Rect    panel;
    int     i;

    render_text_size(r, 12);

    /* Selection/value-only change: the panel is already on screen (overlayDrawn)
     * and the browse view behind it is untouched (bgValid), so repaint just the
     * affected row(s) + the contextual hint — re-filling the whole panel every
     * keystroke was the flash. A value change that DOES invalidate the background
     * (theme / depth / view / artwork / categories / carousel) clears overlayDrawn
     * back in ui_draw, so it falls through to the full draw below. */
    if (u->overlayDrawn) {
        if (u->lastSel != u->setSel && u->lastSel >= 0 && u->lastSel < SET_N)
            draw_settings_row(u, px, py, pw, u->lastSel);
        draw_settings_row(u, px, py, pw, u->setSel);
        draw_settings_hint(u, px, py, pw, ph);
        u->lastSel = u->setSel;
        return;
    }

    SetRect(&panel, px, py, (short)(px + pw), (short)(py + ph));
    render_fill(r, &panel, FILL_PANEL);
    render_frame(r, &panel);

    render_text(r, (short)(px + MARGIN), (short)(py + 22), "Settings", INK_TITLE);
    render_hline(r, px, (short)(px + pw), (short)(py + 30));

    for (i = 0; i < SET_N; i++)
        draw_settings_row(u, px, py, pw, i);

    render_hline(r, px, (short)(px + pw), (short)(py + ph - 22));
    draw_settings_hint(u, px, py, pw, ph);

    u->overlayDrawn = 1;
    u->lastSel = u->setSel;
}

/* The Control Panels list (reached from Settings -> Control Panels): a scrollable
 * panel of the System's `cdev` files; Return opens the selected one via the
 * Finder, Esc returns to Settings. */
static void draw_ctlpanels(Ui *u)
{
    Render *r = u->r;
    int     W = win_w(u), H = win_h(u);
    int     pw = 320;
    int     rows = 9;                       /* visible list rows */
    int     ph = rows * (ROW_H + 2) + 56;
    short   px = (short)((W - pw) / 2);
    short   py = (short)((H - ph) / 2);
    Rect    panel, rr;
    int     i;

    SetRect(&panel, px, py, (short)(px + pw), (short)(py + ph));
    render_fill(r, &panel, FILL_PANEL);
    render_frame(r, &panel);

    render_text_size(r, 12);
    render_text(r, (short)(px + MARGIN), (short)(py + 22), "Control Panels", INK_TITLE);
    render_hline(r, px, (short)(px + pw), (short)(py + 30));

    /* keep the selection in view */
    if (u->cdevSel < u->cdevTop) u->cdevTop = u->cdevSel;
    else if (u->cdevSel >= u->cdevTop + rows) u->cdevTop = u->cdevSel - rows + 1;
    if (u->cdevTop < 0) u->cdevTop = 0;

    if (u->ncdevs == 0) {
        render_text(r, (short)(px + MARGIN), (short)(py + 52),
                    "(none found)", INK_DIM);
    } else {
        for (i = 0; i < rows; i++) {
            int   idx = u->cdevTop + i;
            short y0  = (short)(py + 38 + i * (ROW_H + 2));
            short base = (short)(y0 + ROW_H - 5);
            int   sel = (idx == u->cdevSel);
            char  nm[64];
            const unsigned char *p;
            int   k;
            if (idx >= u->ncdevs) break;
            p = u->cdevs[idx].name;
            for (k = 0; k < p[0] && k < 63; k++) nm[k] = (char)p[k + 1];
            nm[k] = '\0';
            SetRect(&rr, (short)(px + 4), y0, (short)(px + pw - 4), (short)(y0 + ROW_H));
            render_fill(r, &rr, sel ? FILL_SEL : FILL_PANEL);
            render_text(r, (short)(px + MARGIN), base, nm, sel ? INK_SELECTED : INK_NORMAL);
        }
    }

    render_hline(r, px, (short)(px + pw), (short)(py + ph - 22));
    {
        const char *hint = "^v select   Return  open   Esc  back";
        short x = (short)(px + (pw - render_text_width(r, hint)) / 2);
        render_text(r, x, (short)(py + ph - 7), hint, INK_DIM);
    }
}

/* Draw one Menu row (selection highlight + label). Shared by the full-panel draw
 * and the partial (selection-moved) redraw so navigating the menu repaints only
 * the two affected rows instead of re-filling — and flashing — the whole panel. */
static void draw_menu_row(Ui *u, short px, short py, int pw, int i)
{
    Render *r = u->r;
    short   y0   = (short)(py + 36 + i * (ROW_H + 4));
    short   base = (short)(y0 + ROW_H - 5);
    int     sel  = (i == u->menuSel);
    Rect    rr;
    SetRect(&rr, (short)(px + 4), y0, (short)(px + pw - 4), (short)(y0 + ROW_H));
    render_fill(r, &rr, sel ? FILL_SEL : FILL_PANEL);
    render_text(r, (short)(px + MARGIN), base, kMenuLabel[u->menuRows[i]],
                sel ? INK_SELECTED : INK_NORMAL);
}

static void draw_menu(Ui *u)
{
    Render *r = u->r;
    int     W = win_w(u), H = win_h(u);
    int     pw = 240;
    int     ph = u->nmenu * (ROW_H + 4) + 52;
    short   px = (short)((W - pw) / 2);
    short   py = (short)((H - ph) / 2);
    Rect    panel;
    int     i;

    /* Selection-only move: repaint just the previously- and newly-selected rows.
     * The panel is already on screen (overlayDrawn) and the carousel behind it is
     * untouched, so re-filling the whole panel would only flash. */
    if (u->overlayDrawn && u->lastSel != u->menuSel) {
        if (u->lastSel >= 0 && u->lastSel < u->nmenu)
            draw_menu_row(u, px, py, pw, u->lastSel);
        draw_menu_row(u, px, py, pw, u->menuSel);
        u->lastSel = u->menuSel;
        return;
    }

    SetRect(&panel, px, py, (short)(px + pw), (short)(py + ph));
    render_fill(r, &panel, FILL_PANEL);
    render_frame(r, &panel);

    render_text(r, (short)(px + MARGIN), (short)(py + 22), "MacAtrium  Menu", INK_TITLE);
    render_hline(r, px, (short)(px + pw), (short)(py + 30));

    for (i = 0; i < u->nmenu; i++)
        draw_menu_row(u, px, py, pw, i);

    {   /* build stamp (git commit) so the running build is identifiable */
        char  ver[40];
        short vw;
        strcpy(ver, "build ");
        strcat(ver, MACATRIUM_VERSION);
        vw = render_text_width(r, ver);
        render_text(r, (short)(px + (pw - vw) / 2), (short)(py + ph - 9), ver, INK_DIM);
    }

    u->overlayDrawn = 1;
    u->lastSel = u->menuSel;
}

static void draw_preview(Ui *u)
{
    Render *r = u->r;
    int     W = win_w(u), H = win_h(u);
    Rect    full = u->win->portRect;
    Rect    art;
    const CatItem *it = model_cur_item(u->m);

    render_fill(r, &full, FILL_BG);

    /* title */
    render_text_size(r, 12);
    if (it)
        render_text(r, MARGIN, 20, it->name, INK_TITLE);
    render_hline(r, 0, (short)W, (short)(HEADER_H - 1));

    /* art area between header and hint bar */
    SetRect(&art, MARGIN, (short)(HEADER_H + MARGIN),
            (short)(W - MARGIN), (short)(H - HINT_H - MARGIN));
    if (u->previewPic)
        art_draw_fit(u->previewPic, &art);
    else
        render_text(r, MARGIN, (short)(H / 2), "(no artwork)", INK_DIM);

    render_hline(r, 0, (short)W, (short)(H - HINT_H));
    {
        const char *hint = "any key  back";
        short x = (short)((W - render_text_width(r, hint)) / 2);
        render_text(r, x, (short)(H - 7), hint, INK_DIM);
    }
}

/* The More Info card (full screen): title, year/developer, genre, the wrapped
 * description, and the box art shown large on the right. */
static void draw_info(Ui *u)
{
    Render *r = u->r;
    int     W = win_w(u), H = win_h(u);
    Rect    full = u->win->portRect;
    const CatItem *it = model_cur_item(u->m);
    short   artW = (short)(W * 2 / 5);            /* right ~40% for the art */
    short   textR = (short)(W - artW - 2 * MARGIN);
    short   x = MARGIN, y;

    render_fill(r, &full, FILL_BG);
    render_text_size(r, 12);

    if (!it) {
        render_text(r, MARGIN, (short)(H / 2), "(no item selected)", INK_DIM);
        render_hline(r, 0, (short)W, (short)(H - HINT_H));
        return;
    }

    render_text(r, x, 24, it->name, INK_TITLE);
    render_hline(r, 0, (short)W, (short)(HEADER_H - 1));

    y = (short)(HEADER_H + 16);
    {
        char num[16], meta[ITEM_VENDOR_LEN + 24];
        meta[0] = '\0';
        if (it->year > 0) { l2s(it->year, num); strcat(meta, num); }
        if (it->vendor[0]) { if (meta[0]) strcat(meta, " - "); strcat(meta, it->vendor); }
        if (meta[0]) { render_text(r, x, y, meta, INK_NORMAL); y = (short)(y + ROW_H); }
    }
    if (it->genre[0]) {
        char g[ITEM_GENRE_LEN + 8];
        strcpy(g, "Genre: ");
        strncat(g, it->genre, ITEM_GENRE_LEN);
        render_text(r, x, y, g, INK_DIM);
        y = (short)(y + ROW_H);
    }
    y = (short)(y + 8);
    if (it->desc[0]) {
        y = draw_wrapped(r, x, y, textR, ROW_H, it->desc, INK_NORMAL, 10);
    }

    if (u->previewPic) {
        Rect ar;
        SetRect(&ar, (short)(W - artW - MARGIN), (short)(HEADER_H + MARGIN),
                (short)(W - MARGIN), (short)(H - HINT_H - MARGIN));
        art_draw_fit(u->previewPic, &ar);
    } else {
        const char *base = art_base(u, it);
        if (!base || !base[0])
            render_text(r, (short)(W - artW), (short)(H / 2), "(no art)", INK_DIM);
    }

    render_hline(r, 0, (short)W, (short)(H - HINT_H));
    {
        const char *hint = "Return  launch        any other key  back";
        short hx = (short)((W - render_text_width(r, hint)) / 2);
        render_text(r, hx, (short)(H - 7), hint, INK_DIM);
    }
}

/* The About card (Apple > About MacAtrium): app name, a one-line description, and
 * the build stamp. A full-screen card like the Info/Preview views — any key/click
 * dismisses it. */
static void draw_about(Ui *u)
{
    Render *r = u->r;
    int     W = win_w(u), H = win_h(u);
    Rect    full = u->win->portRect;
    short   cy = (short)(H / 2 - 44), cw;
    char    ver[40];

    render_fill(r, &full, FILL_BG);
    render_text_size(r, 12);
    { const char *t = "MacAtrium";
      cw = render_text_width(r, t); render_text(r, (short)((W - cw) / 2), cy, t, INK_TITLE); }
    cy = (short)(cy + 28);
    { const char *t = "A launcher for classic Macintosh games.";
      cw = render_text_width(r, t); render_text(r, (short)((W - cw) / 2), cy, t, INK_NORMAL); }
    cy = (short)(cy + 20);
    { const char *t = "Pick a title and play. The System runs the rest.";
      cw = render_text_width(r, t); render_text(r, (short)((W - cw) / 2), cy, t, INK_DIM); }
    cy = (short)(cy + 30);
    strcpy(ver, "build "); strcat(ver, MACATRIUM_VERSION);
    cw = render_text_width(r, ver); render_text(r, (short)((W - cw) / 2), cy, ver, INK_DIM);

    { const char *t = "Press any key to continue.";
      cw = render_text_width(r, t); render_text(r, (short)((W - cw) / 2), (short)(H - 14), t, INK_DIM); }
}

/* The clickable rect for setup row i (shared by draw_setup + ui_click). */
static void setup_row_rect(Ui *u, int i, Rect *rr)
{
    int W = win_w(u);
    short bx = (short)(MARGIN + 30), bw = (short)(W - 2 * (MARGIN + 30));
    short y0 = (short)(96 + i * 64);
    SetRect(rr, bx, y0, (short)(bx + bw), (short)(y0 + 56));
}

static void draw_setup(Ui *u)
{
    Render *r = u->r;
    int     W = win_w(u), H = win_h(u);
    Rect    full = u->win->portRect, rr;
    short   cw;
    int     i;

    render_fill(r, &full, FILL_BG);
    render_text_size(r, 12);
    { const char *t = "Welcome to MacAtrium";
      cw = render_text_width(r, t); render_text(r, (short)((W - cw) / 2), 40, t, INK_TITLE); }
    { const char *t = "How would you like to browse your library?";
      cw = render_text_width(r, t); render_text(r, (short)((W - cw) / 2), 64, t, INK_NORMAL); }
    render_hline(r, MARGIN, 76, (short)(W - 2 * MARGIN));

    for (i = 0; i < VIEW_N; i++) {
        int sel = (i == u->setupSel);
        setup_row_rect(u, i, &rr);
        render_fill(r, &rr, sel ? FILL_SEL : FILL_PANEL);
        render_frame(r, &rr);
        render_text(r, (short)(rr.left + 14), (short)(rr.top + 22), kViewName[i],
                    sel ? INK_SELECTED : INK_TITLE);
        render_text(r, (short)(rr.left + 14), (short)(rr.top + 42), kViewDesc[i],
                    sel ? INK_SELECTED : INK_DIM);
    }
    { const char *t = "Up / Down to choose, Return to continue.";
      cw = render_text_width(r, t); render_text(r, (short)((W - cw) / 2), (short)(H - 26), t, INK_DIM); }
    { const char *t = "You can change this any time in the View menu.";
      cw = render_text_width(r, t); render_text(r, (short)((W - cw) / 2), (short)(H - 12), t, INK_DIM); }
}

/* Shared browse-screen header: the Settings gear, the centred "^ Category v" band,
 * and the N / M counter (the app title lives in the System menu bar now). Used by
 * the grid view (the carousel draws its own identical header inline). */
static void draw_browse_header(Ui *u)
{
    Render   *r = u->r;
    Model    *m = u->m;
    ModelCat *cat = model_cur_cat(m);
    int       W = win_w(u);
    char      num[16];
    render_text_size(r, 12);
    draw_settings_btn(u);
    if (cat) {
        char  cl[ITEM_CAT_LEN + 8];
        short cw;
        strcpy(cl, "^ "); strcat(cl, cat->name); strcat(cl, " v");
        cw = render_text_width(r, cl);
        render_text(r, (short)((W - cw) / 2), 20, cl, INK_NORMAL);
        {
            char line[24];
            l2s(m->curItem + 1, num); strcpy(line, num); strcat(line, " / ");
            l2s(cat->count, num); strcat(line, num);
            render_text(r, (short)(W - MARGIN - render_text_width(r, line)), 20, line, INK_DIM);
        }
    }
    render_hline(r, 0, (short)W, (short)(HEADER_H - 1));
}

/* A simple vertical scroll bar (track + fixed thumb + ^/v arrows). Classic dither
 * comes with the theme pass; this is the functional mouse-paging affordance. */
#define SBW 16
static void draw_scrollbar_v(Ui *u, short x, short y, short h, int total, int vis, int top)
{
    Render *r = u->r;
    Rect    b;
    SetRect(&b, x, y, (short)(x + SBW), (short)(y + h)); render_frame(r, &b);
    SetRect(&b, x, y, (short)(x + SBW), (short)(y + SBW)); render_frame(r, &b);
    render_text_size(r, 12);
    render_text(r, (short)(x + 5), (short)(y + 12), "^", INK_NORMAL);
    SetRect(&b, x, (short)(y + h - SBW), (short)(x + SBW), (short)(y + h)); render_frame(r, &b);
    render_text(r, (short)(x + 5), (short)(y + h - SBW + 12), "v", INK_NORMAL);
    if (total > vis) {
        short trkY = (short)(y + SBW), trkH = (short)(h - 2 * SBW);
        short thumb = (short)(trkH * vis / total); short pos;
        if (thumb < 16) thumb = 16;
        SetRect(&b, (short)(x + 1), trkY, (short)(x + SBW - 1), (short)(trkY + trkH));
        render_fill(r, &b, FILL_PANEL);
        pos = (short)((long)top * (trkH - thumb) / (total - vis));
        SetRect(&b, (short)(x + 1), (short)(trkY + pos), (short)(x + SBW - 1), (short)(trkY + pos + thumb));
        render_fill(r, &b, FILL_BG); render_frame(r, &b);
    }
}

/* ---- Icon Grid view (Finder "by Icon"): a split pane — icons on the left ~2/3,
 * a detail panel (screenshot + info) on the right ~1/3. ---- */
/* Geometry shared by the grid's draw + click + incremental redraw, so a click and
 * a partial repaint land on the same cell the full draw painted. `scroll` is
 * derived from the selection (keeps it centred/visible). */
typedef struct {
    int   cols, cw, chh, top, vis, n, totRows, scroll, gx0;
    short gridRight;   /* x of the scroll bar (right edge of the icon area) */
    Rect  detail;      /* the right detail panel                            */
} GridLayout;

static void grid_layout(Ui *u, GridLayout *g)
{
    Model    *m = u->m;
    ModelCat *cat = model_cur_cat(m);
    int       W = win_w(u), H = win_h(u), gridW, selRow;
    short     detW = 208;
    if (detW > (short)(W / 2)) detW = (short)(W / 2);
    SetRect(&g->detail, (short)(W - detW), (short)HEADER_H, (short)W, (short)(H - HINT_H));
    g->gridRight = (short)(W - detW - SBW);
    g->cw = 78; g->chh = 62;
    gridW   = g->gridRight - MARGIN;
    g->cols = gridW / g->cw; if (g->cols < 1) g->cols = 1;
    g->top  = HEADER_H + 8;
    g->vis  = (H - HINT_H - g->top) / g->chh; if (g->vis < 1) g->vis = 1;
    g->n    = cat ? cat->count : 0;
    g->totRows = (g->n + g->cols - 1) / g->cols;
    selRow  = m->curItem / g->cols;
    g->scroll = selRow - g->vis / 2;
    if (g->scroll > g->totRows - g->vis) g->scroll = g->totRows - g->vis;
    if (g->scroll < 0) g->scroll = 0;
    g->gx0 = (short)(MARGIN + (gridW - g->cols * g->cw) / 2);
}

/* The cell rect for item `idx`, or 0 if it isn't on the visible page. */
static int grid_cell_rect(const GridLayout *g, int idx, Rect *cell)
{
    int   vis, rrow, ccol;
    short cx, cy;
    if (idx < 0 || idx >= g->n) return 0;
    vis = idx - g->scroll * g->cols;
    if (vis < 0 || vis >= g->vis * g->cols) return 0;
    rrow = vis / g->cols; ccol = vis % g->cols;
    cx = (short)(g->gx0 + ccol * g->cw);
    cy = (short)(g->top + rrow * g->chh);
    SetRect(cell, cx, cy, (short)(cx + g->cw - 4), (short)(cy + g->chh - 4));
    return 1;
}

/* One grid cell (icon + name), selected highlight or normal. A non-selected fill
 * is FILL_BG so repainting a previously-selected cell erases its highlight. */
static void draw_grid_cell(Ui *u, const GridLayout *g, int idx)
{
    Render        *r = u->r;
    Model         *m = u->m;
    ModelCat      *cat = model_cur_cat(m);
    const CatItem *it;
    Art           *ic;
    Rect           cell, ir;
    char           nm[ITEM_NAME_LEN];
    short          isz = 32, ix, nameW;
    int            isSel;
    if (!cat || !grid_cell_rect(g, idx, &cell)) return;
    it = &m->cat->items[cat->idx[idx]]; isSel = (idx == m->curItem);
    render_fill(r, &cell, isSel ? FILL_SEL : FILL_BG);
    ix = (short)(cell.left + (g->cw - 4 - isz) / 2);
    ic = row_icon(u, cat->idx[idx], it);
    SetRect(&ir, ix, (short)(cell.top + 6), (short)(ix + isz), (short)(cell.top + 6 + isz));
    if (ic) art_draw_fit(ic, &ir); else render_frame(r, &ir);
    strncpy(nm, it->name, sizeof nm - 1); nm[sizeof nm - 1] = '\0';
    while (nm[0] && render_text_width(r, nm) > g->cw - 8) nm[strlen(nm) - 1] = '\0';
    nameW = render_text_width(r, nm);
    render_text(r, (short)(cell.left + (g->cw - 4 - nameW) / 2), (short)(cell.bottom - 6), nm,
                isSel ? INK_SELECTED : INK_NORMAL);
}

/* The right detail panel: a left divider, the selected item's screenshot, then its
 * name / year-vendor / genre / blurb (mirrors the carousel's detail band). */
static void draw_grid_detail(Ui *u, const GridLayout *g)
{
    Render        *r = u->r;
    const CatItem *cur = model_cur_item(u->m);
    Rect           d = g->detail, art, dv;
    short          pad = MARGIN, aw, ah, tx, ty;
    char           num[16];

    render_fill(r, &d, FILL_BG);
    SetRect(&dv, d.left, d.top, (short)(d.left + 1), d.bottom);
    render_frame(r, &dv);
    render_text_size(r, 12);

    aw = (short)((d.right - d.left) - 2 * pad);
    ah = (short)(aw * 3 / 4);
    SetRect(&art, (short)(d.left + pad), (short)(d.top + pad),
            (short)(d.left + pad + aw), (short)(d.top + pad + ah));
    draw_detail_art(u, &art);
    if (!cur) return;

    tx = (short)(d.left + pad);
    ty = (short)(art.bottom + 16);
    render_text(r, tx, ty, cur->name, INK_TITLE); ty = (short)(ty + ROW_H + 3);
    {   char buf[ITEM_VENDOR_LEN + 24]; buf[0] = '\0';
        if (cur->year > 0) { l2s(cur->year, num); strcat(buf, num); }
        if (cur->vendor[0]) { if (buf[0]) strcat(buf, " - "); strncat(buf, cur->vendor, sizeof buf - strlen(buf) - 1); }
        if (buf[0]) { render_text(r, tx, ty, buf, INK_DIM); ty = (short)(ty + ROW_H); }
    }
    if (cur->genre[0]) {
        char gg[ITEM_GENRE_LEN + 8]; strcpy(gg, "Genre: "); strncat(gg, cur->genre, ITEM_GENRE_LEN);
        render_text(r, tx, ty, gg, INK_DIM); ty = (short)(ty + ROW_H);
    }
    ty = (short)(ty + 6);
    if (u->status[0])      render_text(r, tx, ty, u->status, INK_NORMAL);
    else if (cur->desc[0]) draw_wrapped(r, tx, ty, aw, ROW_H, cur->desc, INK_NORMAL, 8);
    render_text(r, tx, (short)(d.bottom - 8), "Return  launch    P  box art", INK_DIM);
}

static void draw_iconview(Ui *u)
{
    Render     *r = u->r;
    ModelCat   *cat = model_cur_cat(u->m);
    Rect        full = u->win->portRect;
    int         H = win_h(u), i;
    GridLayout  g;

    render_fill(r, &full, FILL_BG);
    draw_browse_header(u);
    grid_layout(u, &g);
    if (u->r->useOffscreen) ensure_art_loaded(u);   /* detail screenshot, fast path */
    if (!cat || cat->count == 0) {
        const char *t = "(no items in this category)";
        render_text(r, (short)((g.gridRight - render_text_width(r, t)) / 2), (short)(H / 2), t, INK_DIM);
    } else {
        for (i = 0; i < g.vis * g.cols; i++) {
            int idx = g.scroll * g.cols + i;
            if (idx >= g.n) break;
            draw_grid_cell(u, &g, idx);
        }
        draw_scrollbar_v(u, g.gridRight, (short)HEADER_H, (short)(H - HINT_H - HEADER_H), g.totRows, g.vis, g.scroll);
    }
    draw_grid_detail(u, &g);
    u->lastDrawnItem = u->m->curItem;
    u->lastDrawnTop  = g.scroll;
    u->lastDrawnCat  = u->m->curCat;
}

static int iconview_nav(Ui *u, char ch)
{
    Model      *m = u->m;
    GridLayout  g;
    int         idx = m->curItem;
    grid_layout(u, &g);
    switch (ch) {
        case kCharLeft:  model_move_item(m, -1); return 1;
        case kCharRight: model_move_item(m, +1); return 1;
        case kCharUp:
            if (idx < g.cols) { if (!model_move_cat(m, -1)) u->settingsFocus = 1; }
            else model_move_item(m, -g.cols);
            return 1;
        case kCharDown:
            if (idx + g.cols >= g.n) model_move_cat(m, +1);
            else model_move_item(m, +g.cols);
            return 1;
    }
    return 0;
}

/* Click a grid cell: select it; re-click the already-selected cell launches it
 * (so a double-click = select-then-launch, the native open-on-double-click feel). */
static int iconview_click(Ui *u, Point pt, UiCommand *out)
{
    GridLayout g;
    int        i, W = win_w(u);
    short      midX = (short)(W / 2);
    Rect       band;
    SetRect(&band, (short)(midX - CATBAND_HALF), 2, (short)(midX + CATBAND_HALF), (short)(HEADER_H - 2));
    if (PtInRect(pt, &band)) {                        /* "^ Category v" header band */
        model_move_cat(u->m, pt.h < midX ? -1 : +1);
        return 1;
    }
    grid_layout(u, &g);
    if (g.n == 0) return 0;
    for (i = 0; i < g.vis * g.cols; i++) {
        int  idx = g.scroll * g.cols + i;
        Rect cell;
        if (idx >= g.n) break;
        if (grid_cell_rect(&g, idx, &cell) && PtInRect(pt, &cell)) {
            if (idx == u->m->curItem) { u->status[0] = '\0'; *out = UI_LAUNCH; }
            else model_move_item(u->m, idx - u->m->curItem);
            return 1;
        }
    }
    return 0;
}

/* Incremental selection redraw: if the move stayed on the drawn page (same scroll +
 * category), repaint just the old + new cell + the detail panel and blit that union
 * — not the whole window + every icon. Returns 0 (caller does a full draw) when the
 * page scrolled or the category changed. */
static int iconview_draw_sel(Ui *u)
{
    GridLayout g;
    Rect       old, neu, dirty, hdr;
    if (!u->bgValid) return 0;
    grid_layout(u, &g);
    if (g.scroll != u->lastDrawnTop || u->m->curCat != u->lastDrawnCat) return 0;
    render_begin(u->r, u->win);
    SetRect(&hdr, 0, 0, (short)win_w(u), (short)HEADER_H);   /* refresh the N / M counter */
    render_fill(u->r, &hdr, FILL_BG);
    draw_browse_header(u);
    draw_grid_cell(u, &g, u->lastDrawnItem);    /* old -> deselected */
    draw_grid_cell(u, &g, u->m->curItem);       /* new -> selected   */
    draw_grid_detail(u, &g);
    if (!grid_cell_rect(&g, u->lastDrawnItem, &old)) old = g.detail;
    if (!grid_cell_rect(&g, u->m->curItem, &neu)) neu = g.detail;
    UnionRect(&old, &neu, &dirty);
    UnionRect(&dirty, &g.detail, &dirty);
    UnionRect(&dirty, &hdr, &dirty);
    render_end_rect(u->r, u->win, &dirty);
    u->lastDrawnItem = u->m->curItem;
    return 1;
}

/* Deferred screenshot settled: repaint only the detail panel. */
static void iconview_draw_art(Ui *u)
{
    GridLayout g;
    if (!u->bgValid) return;
    grid_layout(u, &g);
    render_begin(u->r, u->win);
    draw_grid_detail(u, &g);
    render_end_rect(u->r, u->win, &g.detail);
}

static int iconview_idle(Ui *u) { return ensure_art_loaded(u) ? UI_IDLE_ART : UI_IDLE_NONE; }

/* ---- List / two-pane browser view ---- */
#define LPANE 152   /* categories pane width */
#define LDET  90    /* bottom detail (screenshot) strip height */

static void vbar(Ui *u, short x, short y, short h)   /* 1px vertical divider */
{
    Rect d; SetRect(&d, x, y, (short)(x + 1), (short)(y + h)); render_frame(u->r, &d);
}

/* Geometry shared by the list's draw + click: the two panes' visible-row windows
 * (first index + row count) and the strip bounds, so a click lands on the same row
 * the draw painted. */
typedef struct {
    short bTop, bBot, lstBot, rx, rw;
    int   catRows, catTop;     /* categories pane: visible rows + first index */
    int   itemRows, itemTop;   /* items pane: visible rows + first index      */
    int   nItems;
} ListLayout;

static void list_layout(Ui *u, ListLayout *L)
{
    Model    *m = u->m;
    ModelCat *cat = model_cur_cat(m);
    int       W = win_w(u), H = win_h(u);
    int       rows, top, n;
    L->bTop   = (short)HEADER_H;
    L->bBot   = (short)(H - HINT_H);
    L->lstBot = (short)(L->bBot - LDET);
    L->rx     = (short)(LPANE + 1);
    L->rw     = (short)(W - LPANE - 1);
    rows = (L->bBot - (L->bTop + 24)) / ROW_H; n = m->ncats;
    top = m->curCat - rows / 2; if (top > n - rows) top = n - rows; if (top < 0) top = 0;
    L->catRows = rows; L->catTop = top;
    n = cat ? cat->count : 0;
    rows = (L->lstBot - (L->bTop + 24)) / ROW_H;
    top = m->curItem - rows / 2; if (top > n - rows) top = n - rows; if (top < 0) top = 0;
    L->itemRows = rows; L->itemTop = top; L->nItems = n;
}

static void draw_listview(Ui *u)
{
    Render        *r = u->r;
    Model         *m = u->m;
    ModelCat      *cat = model_cur_cat(m);
    const CatItem *cur = model_cur_item(m);
    Rect           full = u->win->portRect, rr;
    int            W = win_w(u), i, DET = LDET;
    ListLayout     L;
    short          bTop, bBot, lstBot, rx, rw;
    char           num[16];

    list_layout(u, &L);
    bTop = L.bTop; bBot = L.bBot; lstBot = L.lstBot; rx = L.rx; rw = L.rw;

    render_fill(r, &full, FILL_BG);
    render_text_size(r, 12);
    draw_settings_btn(u);
    render_hline(r, 0, (short)W, (short)(HEADER_H - 1));
    vbar(u, LPANE, bTop, (short)(bBot - bTop));

    /* left pane: categories */
    render_text(r, 8, (short)(bTop + 15), "Categories", INK_TITLE);
    render_hline(r, 0, LPANE, (short)(bTop + 22));
    for (i = 0; i < L.catRows && L.catTop + i < m->ncats; i++) {
        int ci = L.catTop + i, sel = (ci == m->curCat);
        short y0 = (short)(bTop + 26 + i * ROW_H);
        char nm[ITEM_CAT_LEN];
        if (sel) { SetRect(&rr, 1, y0, (short)(LPANE - 1), (short)(y0 + ROW_H)); render_fill(r, &rr, FILL_SEL); }
        strncpy(nm, m->cats[ci].name, sizeof nm - 1); nm[sizeof nm - 1] = '\0';
        while (nm[0] && render_text_width(r, nm) > LPANE - 14) nm[strlen(nm) - 1] = '\0';
        render_text(r, 8, (short)(y0 + ROW_H - 5), nm, sel ? INK_SELECTED : INK_NORMAL);
    }

    /* right pane: the category's items */
    if (cat) {
        char hdr[ITEM_CAT_LEN + 24];
        strcpy(hdr, cat->name); strcat(hdr, "  -  ");
        l2s(cat->count, num); strcat(hdr, num); strcat(hdr, " items");
        render_text(r, (short)(rx + 8), (short)(bTop + 15), hdr, INK_NORMAL);
    }
    render_hline(r, rx, (short)W, (short)(bTop + 22));
    if (cat && cat->count > 0) {
        for (i = 0; i < L.itemRows && L.itemTop + i < L.nItems; i++) {
            int idx = L.itemTop + i, isSel = (idx == m->curItem);
            const CatItem *it = &m->cat->items[cat->idx[idx]];
            short y0 = (short)(bTop + 26 + i * ROW_H);
            char nm[ITEM_NAME_LEN], g[16];
            if (isSel) { SetRect(&rr, rx, y0, (short)(W - SBW), (short)(y0 + ROW_H)); render_fill(r, &rr, FILL_SEL); }
            strncpy(nm, it->name, sizeof nm - 1); nm[sizeof nm - 1] = '\0';
            while (nm[0] && render_text_width(r, nm) > rw - 150) nm[strlen(nm) - 1] = '\0';
            render_text(r, (short)(rx + 8), (short)(y0 + ROW_H - 5), nm, isSel ? INK_SELECTED : INK_NORMAL);
            strncpy(g, it->genre, sizeof g - 1); g[sizeof g - 1] = '\0';
            while (g[0] && render_text_width(r, g) > 74) g[strlen(g) - 1] = '\0';   /* fit before year */
            if (g[0]) render_text(r, (short)(W - SBW - 120), (short)(y0 + ROW_H - 5), g, isSel ? INK_SELECTED : INK_DIM);
            if (it->year > 0) { l2s(it->year, num); render_text(r, (short)(W - SBW - 40), (short)(y0 + ROW_H - 5), num, isSel ? INK_SELECTED : INK_DIM); }
        }
        draw_scrollbar_v(u, (short)(W - SBW), (short)(bTop + 24), (short)(lstBot - (bTop + 24)), L.nItems, L.itemRows, L.itemTop);
    }

    /* bottom detail strip — SCREENSHOT (not box art) + meta */
    render_hline(r, rx, (short)W, lstBot);
    {
        short ay0 = (short)(lstBot + 8), ah = (short)(DET - 18), aw = (short)(ah * 4 / 3);
        Rect ar; int loaded = (cur && cur == u->artFor);
        short mx = (short)(rx + 12 + aw + 14);
        SetRect(&ar, (short)(rx + 12), ay0, (short)(rx + 12 + aw), (short)(ay0 + ah));
        render_frame(r, &ar);
        if (loaded && u->listArt) { Rect in = ar; InsetRect(&in, 2, 2); art_draw_fit(u->listArt, &in); }
        if (cur) {
            char meta[ITEM_GENRE_LEN + 32]; meta[0] = '\0';
            render_text(r, mx, (short)(lstBot + 22), cur->name, INK_TITLE);
            if (cur->year > 0) { l2s(cur->year, num); strcat(meta, num); strcat(meta, "  -  "); }
            if (cur->genre[0]) strcat(meta, cur->genre);
            render_text(r, mx, (short)(lstBot + 40), meta, INK_NORMAL);
            render_text(r, mx, (short)(lstBot + 58), "Return  launch      P  box art", INK_DIM);
        }
    }
}

static int listview_nav(Ui *u, char ch)
{
    Model *m = u->m;
    switch (ch) {
        case kCharUp:    model_move_item(m, -1); return 1;
        case kCharDown:  model_move_item(m, +1); return 1;
        case kCharLeft:  if (!model_move_cat(m, -1)) u->settingsFocus = 1; return 1;
        case kCharRight: model_move_cat(m, +1); return 1;
    }
    return 0;
}
/* List detail screenshot loads deferred; a full repaint shows it (the targeted
 * cover-box redraw is carousel-specific). */
static int listview_idle(Ui *u) { return ensure_art_loaded(u) ? UI_IDLE_FULL : UI_IDLE_NONE; }

/* Click in the List view: a click in the categories pane selects that category and
 * focuses it; a click in the items pane selects that item and focuses the items
 * pane (re-click the selected item launches it). */
static int listview_click(Ui *u, Point pt, UiCommand *out)
{
    Model      *m = u->m;
    ListLayout  L;
    int         i;
    list_layout(u, &L);
    if (pt.h < LPANE) {                                  /* categories pane */
        for (i = 0; i < L.catRows && L.catTop + i < m->ncats; i++) {
            int   ci = L.catTop + i;
            short y0 = (short)(L.bTop + 26 + i * ROW_H);
            Rect  rr; SetRect(&rr, 1, y0, (short)(LPANE - 1), (short)(y0 + ROW_H));
            if (PtInRect(pt, &rr)) {
                u->listFocus = 0;
                if (ci != m->curCat) model_move_cat(m, ci - m->curCat);
                return 1;
            }
        }
        return 0;
    }
    if (pt.v < L.lstBot) {                               /* items pane */
        for (i = 0; i < L.itemRows && L.itemTop + i < L.nItems; i++) {
            int   idx = L.itemTop + i;
            short y0 = (short)(L.bTop + 26 + i * ROW_H);
            Rect  rr; SetRect(&rr, L.rx, y0, (short)(win_w(u) - SBW), (short)(y0 + ROW_H));
            if (PtInRect(pt, &rr)) {
                u->listFocus = 1;
                if (idx == m->curItem) { u->status[0] = '\0'; *out = UI_LAUNCH; }
                else model_move_item(m, idx - m->curItem);
                return 1;
            }
        }
    }
    return 0;
}

/* ---- browse views (MVC strategy) ----------------------------------------
 * Each view renders the shared Model (model.c) in the content area and maps the
 * arrow keys to model moves. The shared keys (Return / Esc / P / I / type-ahead)
 * and the chrome live in ui.c, so a view is just: draw + arrow-nav + mouse-click +
 * deferred-art. */
typedef struct {
    const char *name;
    void (*draw)(Ui *u);
    int  (*nav)(Ui *u, char ch);              /* arrow key → model move; 1 = consumed */
    int  (*idle)(Ui *u);                      /* deferred art load → UI_IDLE_* */
    int  (*click)(Ui *u, Point pt, UiCommand *out); /* hit-test; 1 = handled (*out cmd) */
    int  (*draw_sel)(Ui *u);                  /* incremental selection redraw; 1 = done */
    void (*draw_art)(Ui *u);                  /* targeted detail-art repaint (UI_IDLE_ART) */
} BrowseView;

static int carousel_nav(Ui *u, char ch)
{
    switch (ch) {
        case kCharLeft:  model_move_item(u->m, -1); return 1;   /* scroll games */
        case kCharRight: model_move_item(u->m, +1); return 1;
        case kCharUp:    if (!model_move_cat(u->m, -1)) u->settingsFocus = 1; return 1;
        case kCharDown:  model_move_cat(u->m, +1); return 1;    /* change category */
    }
    return 0;
}
static int carousel_idle(Ui *u) { return ensure_art_loaded(u) ? UI_IDLE_ART : UI_IDLE_NONE; }

/* Carousel deferred cover settled: repaint only the detail cover box (the direct-
 * draw path; the off-screen path already loaded it in draw_carousel). */
static void carousel_draw_art(Ui *u)
{
    CarLayout L;
    Rect      ar;
    render_begin(u->r, u->win);
    carousel_layout(u, &L);
    detail_art_rect(&L, &ar);
    draw_detail_art(u, &ar);
    render_end(u->r, u->win);
}

/* Click in the carousel: the "^ cat v" band changes category; the Launch button
 * launches; the ◀▶ arrows and a visible side tile move the selection. (The shared
 * gear is handled by ui_click before this.) */
static int carousel_click(Ui *u, Point pt, UiCommand *out)
{
    CarLayout L;
    carousel_layout(u, &L);
    if (PtInRect(pt, &L.catBand)) {
        model_move_cat(u->m, pt.h < L.catMidX ? -1 : +1);
        return 1;
    }
    if (L.hasItems) {
        if (PtInRect(pt, &L.launchBtn) && model_cur_item(u->m)) {
            u->status[0] = '\0'; *out = UI_LAUNCH; return 1;
        }
        if (PtInRect(pt, &L.leftArrow))  { model_move_item(u->m, -1); return 1; }
        if (PtInRect(pt, &L.rightArrow)) { model_move_item(u->m, +1); return 1; }
        {   int k;
            for (k = 1; k <= L.nside; k++) {
                short off = (short)(L.half + L.sideGap + L.sideSz / 2 +
                                    (k - 1) * (L.sideSz + L.sideGap));
                short h = (short)(L.sideSz / 2);
                Rect  lt, rt;
                SetRect(&lt, (short)(L.cx - off - h), (short)(L.iconCy - h),
                        (short)(L.cx - off + h), (short)(L.iconCy + h));
                SetRect(&rt, (short)(L.cx + off - h), (short)(L.iconCy - h),
                        (short)(L.cx + off + h), (short)(L.iconCy + h));
                if (L.center - k >= 0 && PtInRect(pt, &lt)) { model_move_item(u->m, -k); return 1; }
                if (L.center + k < L.count && PtInRect(pt, &rt)) { model_move_item(u->m, +k); return 1; }
            }
        }
    }
    return 0;
}

static const BrowseView gCarouselView = { "Carousel",  draw_carousel, carousel_nav, carousel_idle, carousel_click, 0,                 carousel_draw_art };
static const BrowseView gIconView     = { "Icon Grid", draw_iconview, iconview_nav, iconview_idle, iconview_click, iconview_draw_sel, iconview_draw_art };
static const BrowseView gListView     = { "List",      draw_listview, listview_nav, listview_idle, listview_click, 0,                 0 };
static const BrowseView *const gViews[VIEW_N] = {
    &gCarouselView,   /* VIEW_CAROUSEL */
    &gIconView,       /* VIEW_ICON */
    &gListView,       /* VIEW_LIST */
};
static const BrowseView *cur_view(Ui *u)
{
    int v = u->view;
    if (v < 0 || v >= VIEW_N) v = VIEW_CAROUSEL;
    return gViews[v];
}

void ui_draw(Ui *u)
{
    /* Keep the colour backend matched to the live screen depth on *every* repaint,
     * including ones that bypass ui_idle's poll — e.g. the updateEvt the system
     * posts when the screen depth changes (our startup 1-bit->8-bit bump). Without
     * this, that first repaint paints with the stale (B&W) backend and the screen
     * stays black until the user happens to press a key. Lightweight: only re-fits
     * when the depth actually differs; ui_idle still does the full re-fit (art and
     * icon caches are depth-specific). */
    {
        short now = display_current_depth();
        if (u->r->depth != now) render_reset_for_depth(u->r, u->env, now);
    }

    render_begin(u->r, u->win);
    /* On a mode change, force one carousel repaint only when leaving a view that
     * drew *over* the carousel (an overlay panel or a full-screen card) so that
     * panel gets erased. Opening an overlay from the clean LIST/SAFE carousel
     * needs none: the carousel is already in the GWorld, so the panel just
     * composites on top — no needless re-decode of every icon + the cover. */
    if (u->mode != u->lastMode) {
        if (u->lastMode != UI_MODE_LIST)   /* LIST = clean carousel or safe screen */
            u->bgValid = 0;
        u->overlayDrawn = 0;               /* a switched/opened overlay draws fully once */
        u->lastMode = u->mode;
    }
    if (u->mode == UI_MODE_SETUP) {
        draw_setup(u);
        u->bgValid = 0;                 /* full-screen first-run chooser */
    } else if (u->mode == UI_MODE_PREVIEW) {
        draw_preview(u);
        u->bgValid = 0;                 /* full-screen view -> carousel not in GWorld */
    } else if (u->mode == UI_MODE_INFO) {
        draw_info(u);
        u->bgValid = 0;
    } else if (u->mode == UI_MODE_ABOUT) {
        draw_about(u);
        u->bgValid = 0;                 /* full-screen card -> carousel not in GWorld */
    } else {
        /* The menu / settings / control-panels panels are overlays. When only the
         * overlay's selection changed, the carousel behind it is already in the
         * GWorld, so skip repainting it — that's what made menu Up/Down lurch. */
        int overlay = (u->mode == UI_MODE_MENU || u->mode == UI_MODE_SETTINGS ||
                       u->mode == UI_MODE_CTLPANELS);
        if (!overlay || !u->bgValid) {
            if (u->safe) draw_safe(u);
            else         cur_view(u)->draw(u);   /* current browse view (carousel/grid/list) */
            u->bgValid = 1;
            u->overlayDrawn = 0;           /* the repaint erased any overlay panel */
        }
        if (u->mode == UI_MODE_MENU)
            draw_menu(u);
        else if (u->mode == UI_MODE_SETTINGS)
            draw_settings(u);
        else if (u->mode == UI_MODE_CTLPANELS)
            draw_ctlpanels(u);
    }
    render_end(u->r, u->win);
}

int ui_idle(Ui *u)
{
    /* Pick up a screen-depth change made *outside* MacAtrium — the Monitors
     * control panel, or the emulator's own video setting — so colour engages
     * (or B&W falls back) without a trip through our Settings. Our own Settings
     * path goes through apply_depth(); this covers everything else. On a machine
     * with no Color QD (or only 1-bit available) display_current_depth() stays
     * at 1, so this is a no-op. Checked every idle tick (GetMainDevice is cheap). */
    {
        short now = display_current_depth();
        if (now != u->env->pixelSize) {
            u->env->pixelSize = now;
            u->env->useColor  = (u->env->hasColorQD && now >= 4);
            render_reset_for_depth(u->r, u->env, now);
            if (u->listArt) { art_dispose(u->listArt); u->listArt = 0; }
            u->artFor = 0;                       /* art variant is depth-specific  */
            dispose_row_icons(u);                /* icl8/ICN# variant too          */
            u->bgValid = 0;                      /* whole screen must repaint      */
            return UI_IDLE_FULL;
        }
    }

    if (u->safe || u->mode != UI_MODE_LIST) return UI_IDLE_NONE;  /* only the browse view loads art */
    /* Deferred cover load (direct-draw path): repaint ONLY the cover box, not the
     * whole screen — that second full repaint was the "double refresh" on flip. */
    return cur_view(u)->idle(u);
}

/* Repaint only the detail cover/screenshot box (the deferred-load target) — the
 * current view's targeted art repaint. On the off-screen path the cover is loaded
 * synchronously in the view's draw, so this is the direct-path / settle refresh. */
void ui_draw_art(Ui *u)
{
    if (u->safe || u->mode != UI_MODE_LIST) return;
    if (cur_view(u)->draw_art) cur_view(u)->draw_art(u);
}

/* Repaint after a browse-view selection move: an incremental redraw of just the
 * changed cells/detail when the view offers one and is already on-screen, else a
 * full ui_draw (a scroll/category change, an overlay, a non-list mode). This is the
 * Mac update model — redraw only what changed instead of the whole window. */
static void browse_redraw(Ui *u)
{
    if (u->mode == UI_MODE_LIST && !u->safe && u->bgValid &&
        cur_view(u)->draw_sel && cur_view(u)->draw_sel(u))
        return;
    ui_draw(u);
}

/* ---- input ---------------------------------------------------------------- */

static UiCommand menu_select(Ui *u)
{
    switch (u->menuRows[u->menuSel]) {
        case MROW_SETTINGS:    u->mode = UI_MODE_SETTINGS; u->setSel = 0; return UI_NONE;
        case MROW_SHOW_FINDER: u->mode = UI_MODE_LIST; return UI_SHOW_FINDER;
        case MROW_EXIT:        u->mode = UI_MODE_LIST; return UI_QUIT;
        case MROW_RESTART:     u->mode = UI_MODE_LIST; return UI_RESTART;
        case MROW_SHUTDOWN:    u->mode = UI_MODE_LIST; return UI_SHUTDOWN;
    }
    u->mode = UI_MODE_LIST;
    return UI_NONE;
}

/* Build "<base>.<depth>.<ext>" into buf (depth is 1/4/8/16). */
static void art_variant_path(char *buf, const char *base, int depth, const char *ext)
{
    int n;
    strcpy(buf, base);
    n = (int)strlen(buf);
    buf[n++] = '.';
    if (depth >= 10) { buf[n++] = (char)('0' + depth / 10); buf[n++] = (char)('0' + depth % 10); }
    else             { buf[n++] = (char)('0' + depth); }
    buf[n++] = '.';
    strcpy(buf + n, ext);
}

/* Load the depth variant for `base`. 1-bit art ships as a raw CopyBits bitmap
 * (.raw) — preferred over a .pict because DrawPicture faults Snow on some valid
 * 1-bit art (docs/14); fall back to a .pict variant if the .raw is absent. */
static Art *load_variant(const char *base, int depth)
{
    char buf[208];
    Art *p;
    if (depth == 1) {
        art_variant_path(buf, base, 1, "raw");
        p = art_load(buf);
        if (p) return p;
    }
    art_variant_path(buf, base, depth, "pict");
    return art_load(buf);
}

/* Resolve an item's `image` to an Art. An explicit ".pict"/".raw" path loads
 * directly; otherwise it's a base path and we pick the depth variant matching
 * the screen (e.g. "images/foo" -> "images/foo.1.raw" on a 1-bit screen),
 * falling back to shallower depths then "<base>.pict"/".raw". This keeps a
 * 1-bit screen from ever drawing a colour PICT (docs/06 depth variants). */
static Art *load_item_art(Ui *u, const char *image)
{
    int n = (int)strlen(image);
    char buf[208];
    Art *p;
    int cand[5], nc = 0, i, depth;

    if ((n >= 5 && strcmp(image + n - 5, ".pict") == 0) ||
        (n >= 4 && strcmp(image + n - 4, ".raw") == 0))
        return art_load(image);

    /* Pick the best available variant for the screen depth: the native depth
     * first, then *higher* depths (QuickDraw down-converts a deeper PICT to the
     * screen — docs/15, verified), then *lower* colour depths, and the 1-bit raw
     * last. So a single deep master (e.g. `<id>.24.pict`) covers every colour
     * screen, while a 1-bit screen still prefers the ordered-dither `<id>.1.raw`.
     * (Encoder depths: 1/4/8 indexed, 16/24 direct.) */
    depth = u->env->pixelSize;
    if      (depth <= 1)  { cand[nc++]=1;  cand[nc++]=8;  cand[nc++]=16; cand[nc++]=24; cand[nc++]=4; }
    else if (depth <= 4)  { cand[nc++]=4;  cand[nc++]=8;  cand[nc++]=16; cand[nc++]=24; cand[nc++]=1; }
    else if (depth <= 8)  { cand[nc++]=8;  cand[nc++]=16; cand[nc++]=24; cand[nc++]=4;  cand[nc++]=1; }
    else if (depth <= 16) { cand[nc++]=16; cand[nc++]=24; cand[nc++]=8;  cand[nc++]=4;  cand[nc++]=1; }
    else                  { cand[nc++]=24; cand[nc++]=16; cand[nc++]=8;  cand[nc++]=4;  cand[nc++]=1; }

    for (i = 0; i < nc; i++) {
        p = load_variant(image, cand[i]);
        if (p) return p;
    }
    strcpy(buf, image);
    strcat(buf, ".pict");
    p = art_load(buf);
    if (p) return p;
    strcpy(buf, image);
    strcat(buf, ".raw");
    p = art_load(buf);
    if (p) return p;
    /* last resort: the app's own Finder icon, baked as a raw bitmap (docs/14). */
    strcpy(buf, image);
    strcat(buf, ".icon.raw");
    return art_load(buf);
}

/* Switch the screen to `depth` bits and re-fit our rendering to it. */
static void apply_depth(Ui *u, short depth)
{
    if (display_set_depth(depth) != noErr) return;
    u->env->pixelSize = display_current_depth();   /* re-read what we actually got */
    /* Persist it as the boot default in slot PRAM so the system comes up here next
     * time (the launcher then just matches it). main also saves the depth to prefs. */
    (void)display_set_default_depth(u->env->pixelSize);
    u->env->useColor  = (u->env->hasColorQD && u->env->pixelSize >= 4);
    render_reset_for_depth(u->r, u->env, u->env->pixelSize);
    if (u->listArt) {                              /* art variant is depth-specific */
        art_dispose(u->listArt); u->listArt = 0; u->artFor = 0;
    }
    dispose_row_icons(u);                          /* icl8/ICN# variant is depth-specific */
    u->bgValid = 0;                                /* whole screen must repaint */
}

/* Change the selected Settings row's value by `dir` (-1 / +1). Returns 1 if a
 * *persisted* preference (theme / volume / colour depth) changed, so main can
 * save prefs. Colour depth now persists via slot PRAM (apply_depth →
 * display_set_default_depth) plus the prefs `depth` key (docs/15). */
static int settings_adjust(Ui *u, int dir)
{
    switch (u->setSel) {
        case 0:                                    /* Theme (persisted) */
            render_toggle_theme(u->r);
            u->bgValid = 0;                         /* carousel colours changed */
            return 1;
        case 1: {                                  /* Color Depth (persisted) */
            int i, cur = 0;
            for (i = 0; i < u->ndepths; i++)
                if (u->depths[i] == u->env->pixelSize) cur = i;
            cur += dir;
            if (cur < 0) cur = 0;
            if (cur >= u->ndepths) cur = u->ndepths - 1;
            if (u->ndepths > 0 && u->depths[cur] != u->env->pixelSize) {
                apply_depth(u, u->depths[cur]);
                return 1;                           /* persist the new boot depth */
            }
            return 0;
        }
        case 2:                                    /* Volume (persisted) */
            if (u->vol >= 0) {
                int old = u->vol;
                u->vol += dir;
                if (u->vol < 0) u->vol = 0;
                if (u->vol > SOUND_VOL_MAX) u->vol = SOUND_VOL_MAX;
                sound_set_vol(u->vol);
                return (u->vol != old);
            }
            return 0;
        case 3:                                    /* Artwork: Box Art / Screenshot */
            u->artPref = u->artPref ? 0 : 1;
            if (u->listArt) { art_dispose(u->listArt); u->listArt = 0; }
            u->artFor = 0;                          /* force the detail pane to reload */
            u->bgValid = 0;                         /* carousel art changes */
            return 1;                               /* persisted */
        case 4:                                    /* Startup Sound On/Off (persisted) */
            u->sndStartup = u->sndStartup ? 0 : 1;
            if (u->sndStartup) sound_play_file("sounds/startup", 1);   /* preview */
            return 1;
        case 5:                                    /* Shutdown Sound On/Off (persisted) */
            u->sndShutdown = u->sndShutdown ? 0 : 1;
            if (u->sndShutdown) sound_play_file("sounds/shutdown", 1); /* preview */
            return 1;
        case 6:                                    /* View: Carousel / Icon Grid / List (persisted) */
            u->view = (u->view + dir + VIEW_N) % VIEW_N;
            u->bgValid = 0;                         /* the whole browse screen changes */
            return 1;
        case 7:                                    /* Categories list Show/Hide (persisted) */
            u->catList = u->catList ? 0 : 1;
            u->bgValid = 0;                         /* browse layout changes */
            return 1;
        case 8: {                                  /* Carousel icon count: odd 3..25 (persisted) */
            int n = u->carousel + dir * 2;
            if (n < 3)  n = 3;
            if (n > 25) n = 25;
            if (n == u->carousel) return 0;
            u->carousel = n;
            u->bgValid = 0;                         /* carousel layout changes */
            return 1;
        }
        default:                                   /* Control Panels (action row, intercepted) */
            return 0;
    }
}

UiCommand ui_key(Ui *u, char ch)
{
    UiCommand cmd = UI_NONE;

    /* First-run chooser is modal: Up/Down pick, Return/Esc confirm + persist. */
    if (u->mode == UI_MODE_SETUP) {
        UiCommand sc = UI_NONE;
        switch (ch) {
            case kCharUp:    if (u->setupSel > 0) u->setupSel--; break;
            case kCharDown:  if (u->setupSel < VIEW_N - 1) u->setupSel++; break;
            case kCharReturn:
            case kCharEnter:
            case kCharEscape:
                u->view = u->setupSel;
                u->mode = UI_MODE_LIST;
                u->bgValid = 0;
                sc = UI_PREFS_DIRTY;        /* persist the view + mark first-run done */
                break;
        }
        ui_draw(u);                         /* redraw the chooser (or the carousel on confirm) */
        return sc;
    }

    /* Theme toggle works in any mode (list / menu / safe / preview). */
    if (ch == 't' || ch == 'T') {
        render_toggle_theme(u->r);
        u->bgValid = 0;                             /* colours changed everywhere */
        ui_draw(u);
        return UI_PREFS_DIRTY;                      /* theme changed -> persist */
    }

    /* Tab cycles the browse view (Carousel -> Icon -> List) — interim until the
     * View menu lands; persisted. */
    if (ch == '\t' && u->mode == UI_MODE_LIST && !u->settingsFocus && !u->safe) {
        u->view = (u->view + 1) % VIEW_N;
        u->bgValid = 0;
        ui_draw(u);
        return UI_PREFS_DIRTY;
    }

    /* Settings panel: rows adjusted with arrows, Esc returns to the list. */
    if (u->mode == UI_MODE_SETTINGS) {
        int dirty = 0;
        /* The Control Panels row is an action: Return/Right opens the cdev list
         * (enumerated fresh each time). */
        if (u->setSel == SET_ROW_CTLPANELS &&
            (ch == kCharReturn || ch == kCharEnter || ch == kCharRight)) {
            u->ncdevs  = ctlpanels_list(u->cdevs, CTLPANEL_MAX);
            u->cdevSel = 0;
            u->cdevTop = 0;
            u->mode = UI_MODE_CTLPANELS;
            ui_draw(u);
            return UI_NONE;
        }
        switch (ch) {
            case kCharUp:    if (u->setSel > 0) u->setSel--; break;
            case kCharDown:  if (u->setSel < SET_N - 1) u->setSel++; break;
            case kCharLeft:  dirty = settings_adjust(u, -1); break;
            case kCharRight: dirty = settings_adjust(u, +1); break;
            case kCharReturn:
            case kCharEnter: dirty = settings_adjust(u, +1); break;
            case kCharEscape: u->mode = UI_MODE_LIST; break;   /* gear stays focused */
        }
        ui_draw(u);
        return dirty ? UI_PREFS_DIRTY : UI_NONE;
    }

    /* Control Panels list: navigate, Return opens via the Finder, Esc back. */
    if (u->mode == UI_MODE_CTLPANELS) {
        switch (ch) {
            case kCharUp:    if (u->cdevSel > 0) u->cdevSel--; break;
            case kCharDown:  if (u->cdevSel < u->ncdevs - 1) u->cdevSel++; break;
            case kCharReturn:
            case kCharEnter:
                if (u->ncdevs > 0) { ui_draw(u); return UI_OPEN_CDEV; }
                break;
            case kCharEscape: u->mode = UI_MODE_SETTINGS; break;
        }
        ui_draw(u);
        return UI_NONE;
    }

    /* Gear focused on the list screen (reached by Left at the first category). */
    if (u->mode == UI_MODE_LIST && u->settingsFocus) {
        switch (ch) {
            case kCharReturn:
            case kCharEnter:  u->mode = UI_MODE_SETTINGS; u->setSel = 0; break;
            case kCharEscape: u->settingsFocus = 0; u->mode = UI_MODE_MENU; u->menuSel = 0; break;
            default:          u->settingsFocus = 0; break;   /* any other key unfocuses */
        }
        ui_draw(u);
        return UI_NONE;
    }

    /* About card: any key returns to the list. */
    if (u->mode == UI_MODE_ABOUT) {
        u->mode = UI_MODE_LIST;
        ui_draw(u);
        return UI_NONE;
    }

    /* Preview mode: any other key returns to the list. */
    if (u->mode == UI_MODE_PREVIEW) {
        art_dispose(u->previewPic);
        u->previewPic = 0;
        u->mode = UI_MODE_LIST;
        ui_draw(u);
        return UI_NONE;
    }

    /* More Info: Return launches the title; any other key returns to the list. */
    if (u->mode == UI_MODE_INFO) {
        art_dispose(u->previewPic);
        u->previewPic = 0;
        u->mode = UI_MODE_LIST;
        if ((ch == kCharReturn || ch == kCharEnter) && model_cur_item(u->m)) {
            u->status[0] = '\0';
            ui_draw(u);
            return UI_LAUNCH;
        }
        ui_draw(u);
        return UI_NONE;
    }

    if (u->mode == UI_MODE_MENU) {
        switch (ch) {
            case kCharUp:    if (u->menuSel > 0) u->menuSel--; break;
            case kCharDown:  if (u->menuSel < u->nmenu - 1) u->menuSel++; break;
            case kCharReturn:
            case kCharEnter: cmd = menu_select(u); break;
            case kCharEscape: u->mode = UI_MODE_LIST; break;
        }
        ui_draw(u);
        return cmd;
    }

    /* Per-item launch hotkey: a printable key mapped to a title launches it
     * immediately (doubles as a gamepad button via MiSTer's button->key map).
     * Checked before navigation/type-ahead; restricted to printable keys so it
     * never shadows the arrows / Return / Esc. (Note 't' is consumed by the
     * global theme toggle above, so it can't be a hotkey.) */
    if (!u->safe && (unsigned char)ch >= 0x20 && model_select_hotkey(u->m, ch)) {
        u->status[0] = '\0';
        ui_draw(u);
        return UI_LAUNCH;
    }

    /* list / safe mode — the current browse view owns arrow navigation; the
     * shared keys (Esc / Return / P / I / type-ahead) below apply to every view. */
    if (!u->safe && cur_view(u)->nav(u, ch)) {
        browse_redraw(u);           /* incremental when the move stayed on-page */
        return cmd;                 /* cmd == UI_NONE here */
    }
    switch (ch) {
        case kCharEscape:
            u->mode = UI_MODE_MENU;
            u->menuSel = 0;
            break;
        case kCharReturn:
        case kCharEnter:
            if (!u->safe && model_cur_item(u->m)) {
                u->status[0] = '\0';
                cmd = UI_LAUNCH;
            }
            break;
        case 'p':
        case 'P':
            if (!u->safe) {
                const CatItem *it = model_cur_item(u->m);
                /* Box art on demand: the main pane shows the screenshot, so P is
                 * the way to see the box/cover art full-screen (falls back to the
                 * screenshot when a title has no box art). */
                const char *base = it ? (it->image[0] ? it->image : it->shot) : 0;
                if (base && base[0]) {
                    u->previewPic = load_item_art(u, base);
                    u->mode = UI_MODE_PREVIEW;   /* draws "(no artwork)" if load failed */
                }
            }
            break;
        case 'i':
        case 'I':
            /* More Info card for the selection (loads its art, like preview). */
            if (!u->safe) {
                const CatItem *it = model_cur_item(u->m);
                if (it) {
                    const char *base = art_base(u, it);
                    if (base && base[0]) u->previewPic = load_item_art(u, base);
                    u->mode = UI_MODE_INFO;
                }
            }
            break;
        default:
            /* Type-ahead: any other printable key jumps to the next matching
             * item. ('t'/'p' stay reserved for theme/preview above.) */
            if (!u->safe &&
                ((ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') ||
                 (ch >= '0' && ch <= '9')))
                model_type_ahead(u->m, ch);
            break;
    }
    /* Launching hands off to the game and tears down the launcher window, so the
     * pre-launch repaint was a wasted full-screen blit the user saw flash by. */
    if (cmd != UI_LAUNCH) ui_draw(u);
    return cmd;
}

/* Mouse equivalent of ui_key: hit-test a window-local click (main does the
 * GlobalToLocal) and return the same UiCommand the keyboard path would, redrawing
 * first so the click gives immediate feedback. Mirrors ui_key's per-mode shape.
 * Browse screen: the gear opens the menu hub; the ◀▶ arrows and a side tile move
 * the selection; the centred "^ cat v" band changes category (left half = prev,
 * right = next); the Launch button launches. Modal panels hit-test their rows and
 * dismiss on a click outside the panel (the universal mouse "Back"). */
UiCommand ui_click(Ui *u, Point pt)
{
    /* First-run chooser: a click on a row picks that view and continues. */
    if (u->mode == UI_MODE_SETUP) {
        int i;
        for (i = 0; i < VIEW_N; i++) {
            Rect rr; setup_row_rect(u, i, &rr);
            if (PtInRect(pt, &rr)) {
                u->setupSel = i; u->view = i;
                u->mode = UI_MODE_LIST; u->bgValid = 0;
                ui_draw(u);
                return UI_PREFS_DIRTY;
            }
        }
        return UI_NONE;
    }

    /* Safe (no-catalog) screen: a click opens the Esc menu so Restart / Shut Down
     * stay reachable with the mouse. */
    if (u->safe) {
        u->mode = UI_MODE_MENU; u->menuSel = 0;
        ui_draw(u);
        return UI_NONE;
    }

    if (u->mode == UI_MODE_MENU) {
        int   W = win_w(u), H = win_h(u);
        int   pw = 240, ph = u->nmenu * (ROW_H + 4) + 44;
        short px = (short)((W - pw) / 2), py = (short)((H - ph) / 2);
        Rect  panel;
        int   i;
        SetRect(&panel, px, py, (short)(px + pw), (short)(py + ph));
        if (!PtInRect(pt, &panel)) { u->mode = UI_MODE_LIST; ui_draw(u); return UI_NONE; }
        for (i = 0; i < u->nmenu; i++) {
            short y0 = (short)(py + 36 + i * (ROW_H + 4));
            Rect  rr;
            SetRect(&rr, (short)(px + 4), y0, (short)(px + pw - 4), (short)(y0 + ROW_H));
            if (PtInRect(pt, &rr)) {
                UiCommand c;
                u->menuSel = i;
                c = menu_select(u);
                ui_draw(u);
                return c;
            }
        }
        ui_draw(u);
        return UI_NONE;
    }

    if (u->mode == UI_MODE_SETTINGS) {
        int   W = win_w(u), H = win_h(u);
        int   pw = 320, ph = SET_N * (ROW_H + 6) + 56;
        short px = (short)((W - pw) / 2), py = (short)((H - ph) / 2);
        Rect  panel;
        int   i, dirty = 0;
        SetRect(&panel, px, py, (short)(px + pw), (short)(py + ph));
        if (!PtInRect(pt, &panel)) { u->mode = UI_MODE_LIST; ui_draw(u); return UI_NONE; }
        for (i = 0; i < SET_N; i++) {
            short y0 = (short)(py + 40 + i * (ROW_H + 6));
            Rect  rr;
            SetRect(&rr, (short)(px + 4), y0, (short)(px + pw - 4), (short)(y0 + ROW_H));
            if (PtInRect(pt, &rr)) {
                if (i == SET_ROW_CTLPANELS) {        /* action row: open the cdev list */
                    u->ncdevs  = ctlpanels_list(u->cdevs, CTLPANEL_MAX);
                    u->cdevSel = 0; u->cdevTop = 0;
                    u->mode = UI_MODE_CTLPANELS;
                } else if (i == u->setSel) {         /* re-click the selected row adjusts */
                    dirty = settings_adjust(u, +1);
                } else {                             /* first click just selects */
                    u->setSel = i;
                }
                break;
            }
        }
        ui_draw(u);
        return dirty ? UI_PREFS_DIRTY : UI_NONE;
    }

    if (u->mode == UI_MODE_CTLPANELS) {
        int   W = win_w(u), H = win_h(u);
        int   pw = 320, rows = 9, ph = rows * (ROW_H + 2) + 56;
        short px = (short)((W - pw) / 2), py = (short)((H - ph) / 2);
        Rect  panel;
        int   i;
        SetRect(&panel, px, py, (short)(px + pw), (short)(py + ph));
        if (!PtInRect(pt, &panel)) { u->mode = UI_MODE_SETTINGS; ui_draw(u); return UI_NONE; }
        for (i = 0; i < rows; i++) {
            int   idx = u->cdevTop + i;
            short y0  = (short)(py + 38 + i * (ROW_H + 2));
            Rect  rr;
            if (idx >= u->ncdevs) break;
            SetRect(&rr, (short)(px + 4), y0, (short)(px + pw - 4), (short)(y0 + ROW_H));
            if (PtInRect(pt, &rr)) {
                if (idx == u->cdevSel) { ui_draw(u); return UI_OPEN_CDEV; }  /* re-click opens */
                u->cdevSel = idx;
                break;
            }
        }
        ui_draw(u);
        return UI_NONE;
    }

    /* Full-screen info / preview / about cards: any click returns to the list. */
    if (u->mode == UI_MODE_INFO || u->mode == UI_MODE_PREVIEW || u->mode == UI_MODE_ABOUT) {
        if (u->previewPic) { art_dispose(u->previewPic); u->previewPic = 0; }
        u->mode = UI_MODE_LIST;
        ui_draw(u);
        return UI_NONE;
    }

    /* ---- browse screen (UI_MODE_LIST) ---- */
    {
        UiCommand cmd = UI_NONE;
        Rect      gear;
        SetRect(&gear, (short)(GEAR_X - 4), 3, (short)(GEAR_X + GEAR_W - 4), (short)(HEADER_H - 2));
        u->settingsFocus = 0;                        /* a click takes focus off the gear */

        if (PtInRect(pt, &gear)) {                   /* shared: gear -> the menu hub */
            u->mode = UI_MODE_MENU; u->menuSel = 0;
            ui_draw(u);
            return UI_NONE;
        }
        /* The active view owns selection / launch / category hit-testing. */
        if (cur_view(u)->click && cur_view(u)->click(u, pt, &cmd)) {
            if (cmd != UI_LAUNCH) browse_redraw(u);  /* a launch tears down the window */
            return cmd;
        }
        ui_draw(u);
        return UI_NONE;
    }
}

/* ---- menu-bar entry points (called by main.c's MenuSelect/MenuKey dispatch) ----
 * Thin wrappers so the System menu bar drives the same state the keyboard does;
 * each dismisses any open panel/card first, sets the new mode/state, and repaints. */
void ui_show_about(Ui *u)
{
    u->mode = UI_MODE_ABOUT;
    ui_draw(u);
}

void ui_show_settings(Ui *u)
{
    u->settingsFocus = 0;
    u->setSel = 0;
    u->mode = UI_MODE_SETTINGS;
    ui_draw(u);
}

void ui_show_info(Ui *u)
{
    const CatItem *it;
    if (u->safe) return;
    if (u->previewPic) { art_dispose(u->previewPic); u->previewPic = 0; }
    it = model_cur_item(u->m);
    if (it) {
        const char *base = art_base(u, it);
        if (base && base[0]) u->previewPic = load_item_art(u, base);
        u->mode = UI_MODE_INFO;
    } else {
        u->mode = UI_MODE_LIST;
    }
    ui_draw(u);
}

void ui_set_view(Ui *u, int view)
{
    if (view < 0 || view >= VIEW_N) return;
    u->settingsFocus = 0;
    u->mode = UI_MODE_LIST;            /* dismiss any panel so the new view shows */
    if (u->view != view) { u->view = view; u->bgValid = 0; }
    ui_draw(u);
}
