from PIL import Image, ImageDraw

# ---------- shared geometry (drawn at scale s) ----------
def draw_greenhouse(s, color):
    W = 32 * s
    img = Image.new('RGB', (W, W), (255,255,255))
    d = ImageDraw.Draw(img)
    def S(p): return (p[0]*s, p[1]*s)
    GREEN=(34,120,52); GLASS=(176,216,226); DOOR=(120,72,40); SOIL=(70,110,55)
    fg = GREEN if color else (0,0,0)
    roof=[(15,2),(28,13),(3,13)]
    if color:
        d.polygon([S(p) for p in roof], fill=GLASS)
        d.rectangle([S((4,13)),S((27,29))], fill=GLASS)
        d.rectangle([S((13,22)),S((18,29))], fill=DOOR)
    lw=max(1,s)
    d.line([S((15,2)),S((28,13))], fill=fg, width=lw)
    d.line([S((15,2)),S((3,13))], fill=fg, width=lw)
    d.line([S((3,13)),S((28,13))], fill=fg, width=lw)
    d.line([S((15,2)),S((15,13))], fill=fg, width=lw)
    for ex in (9,21): d.line([S((15,2)),S((ex,13))], fill=fg, width=lw)
    d.rectangle([S((4,13)),S((27,29))], outline=fg, width=lw)
    for x in (10,21): d.line([S((x,14)),S((x,29))], fill=fg, width=lw)
    d.line([S((5,21)),S((26,21))], fill=fg, width=lw)
    d.rectangle([S((13,22)),S((18,29))], outline=fg, width=lw)
    d.line([S((1,30)),S((30,30))], fill=(SOIL if color else (0,0,0)), width=max(1,s))
    return img

def silhouette():
    m = Image.new('L',(32,32),0); dm=ImageDraw.Draw(m)
    dm.polygon([(15,2),(28,13),(3,13)], fill=255)
    dm.rectangle([4,13,27,29], fill=255)
    dm.rectangle([1,29,30,30], fill=255)   # ground
    return m

# ---------- 1-bit ICN# + mask ----------
ic1 = draw_greenhouse(1, color=False).convert('L')
mask = silhouette()
def pack_1bit(get, w, h):
    rb=(w+7)//8; out=bytearray()
    for y in range(h):
        for bx in range(rb):
            b=0
            for bit in range(8):
                x=bx*8+bit
                if x<w and get(x,y): b|=(1<<(7-bit))
            out.append(b)
    return bytes(out)
icon32 = pack_1bit(lambda x,y: ic1.getpixel((x,y))==0, 32,32)   # black frame -> 1
mask32 = pack_1bit(lambda x,y: mask.getpixel((x,y))>0, 32,32)

# ---------- icl8 (32x32 8-bit, Mac palette) ----------
def mac_palette():
    CUBE=[0xFF,0xCC,0x99,0x66,0x33,0x00]; RAMP=[0xEE,0xDD,0xBB,0xAA,0x88,0x77,0x55,0x44,0x22,0x11]
    pal=[(r,g,b) for r in CUBE for g in CUBE for b in CUBE]
    pal+=[(v,0,0) for v in RAMP]+[(0,v,0) for v in RAMP]+[(0,0,v) for v in RAMP]+[(v,v,v) for v in RAMP]
    return pal
PAL=mac_palette()
def nearest(rgb): return min(range(256), key=lambda i: sum((PAL[i][k]-rgb[k])**2 for k in range(3)))
icc = draw_greenhouse(1, color=True)
icl8 = bytearray()
for y in range(32):
    for x in range(32):
        icl8.append(0 if mask.getpixel((x,y))==0 else nearest(icc.getpixel((x,y))))

# ---------- 16x16 ics# + ics8 ----------
ic1_16 = ic1.resize((16,16), Image.NEAREST)
mask_16 = mask.resize((16,16), Image.NEAREST)
ics_icon = pack_1bit(lambda x,y: ic1_16.getpixel((x,y))<128, 16,16)
ics_mask = pack_1bit(lambda x,y: mask_16.getpixel((x,y))>0, 16,16)
icc16 = icc.resize((16,16), Image.NEAREST)
ics8 = bytearray()
for y in range(16):
    for x in range(16):
        ics8.append(0 if mask_16.getpixel((x,y))==0 else nearest(icc16.getpixel((x,y))))

def hx(b): return ''.join(f'{x:02X}' for x in b)
def rez_data(t,i,b,comment=''):
    s=hx(b); lines=[s[j:j+64] for j in range(0,len(s),64)]
    body=' '.join(f'$"{l}"' for l in lines)
    return f"data '{t}' ({i}) {{  /* {comment} */\n    {body}\n}};\n"

ICN = icon32+mask32                       # 256 bytes
icsh = ics_icon+ics_mask                  # 64 bytes
# signature 'ATRM' (0): a pascal version string
sig = bytes([len('MacAtrium 1.0')])+b'MacAtrium 1.0'
# FREF (128): 'APPL', iconLocalID 0, empty name
fref = b'APPL'+bytes([0,0])+bytes([0])
# BNDL (128): owner 'ATRM' id 0, 2 types (ICN# + FREF), each local0->128
bndl = b'ATRM'+bytes([0,0])+bytes([0,1]) \
     + b'ICN#'+bytes([0,0])+bytes([0,0,0,128]) \
     + b'FREF'+bytes([0,0])+bytes([0,0,0,128])

with open('/tmp/macatrium-icon.r','w') as f:
    f.write("/* macatrium-icon.r -- the launcher's Finder icon: a greenhouse\n")
    f.write(" * ('atrium' = a glass-roofed court). Generated by tools/gh_emit.py.\n")
    f.write(" * Emitted as raw `data` resources so no Rez type template is needed. */\n\n")
    f.write(rez_data('ICN#',128,ICN,'32x32 1-bit icon + mask'))
    f.write(rez_data('icl8',128,bytes(icl8),'32x32 8-bit colour'))
    f.write(rez_data('ics#',128,icsh,'16x16 1-bit icon + mask'))
    f.write(rez_data('ics8',128,bytes(ics8),'16x16 8-bit colour'))
    f.write(rez_data('FREF',128,fref,'APPL -> icon local 0'))
    f.write(rez_data('BNDL',128,bndl,'bundle: ICN#/FREF -> 128'))
    f.write(rez_data('ATRM',0,sig,'signature / version'))

# ---------- GUI brand PNGs (greenhouse, hi-res) ----------
big = draw_greenhouse(8, color=True)   # 256x256
big.save('/tmp/macatrium-256.png')
big.resize((128,128), Image.LANCZOS).save('/tmp/macatrium-128.png')
big.save('/tmp/macatrium.ico', sizes=[(16,16),(32,32),(48,48),(64,64),(128,128),(256,256)])
print("wrote /tmp/macatrium-icon.r and GUI PNGs; ICN#",len(ICN),"icl8",len(icl8),"bytes")
